/* GENERATED BY PAYLOAD, extended locally: custom.scss import + Poppins wrapper
 * (brand overlay — see src/app/(payload)/custom.scss). Re-apply if Payload regenerates. */
import config from '@payload-config'
import '@payloadcms/next/css'
import type { ServerFunctionClient } from 'payload'
import { handleServerFunctions, RootLayout } from '@payloadcms/next/layouts'
import { Poppins } from 'next/font/google'
import React from 'react'

import { importMap } from './admin/importMap.js'
import './custom.scss'
/* Tailwind utilities + shared brand tokens for the custom auth views — must come
   AFTER custom.scss so its cascade layers outrank Payload's `payload-default`. */
import './admin.css'

/* Same self-hosted Poppins as the frontend layout — the admin follows the brand (§12). */
const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  variable: '--font-poppins',
})

type Args = {
  children: React.ReactNode
}

const serverFunction: ServerFunctionClient = async function (args) {
  'use server'
  return handleServerFunctions({
    ...args,
    config,
    importMap,
  })
}

const Layout = ({ children }: Args) => (
  <RootLayout config={config} importMap={importMap} serverFunction={serverFunction}>
    {/* display:contents wrapper (custom.scss) — cascades Poppins + brand vars without
        touching Payload's own layout tree */}
    <div className={`${poppins.variable} isad-admin-theme`}>{children}</div>
  </RootLayout>
)

export default Layout
