/**
 * Shared SEO constants/helpers (T14). The canonical origin comes from
 * `NEXT_PUBLIC_SITE_URL` (CLAUDE.md §2) — falls back to the dev server origin so
 * local/preview environments always produce absolute URLs.
 */

export const SITE_NAME = 'isad.academy'

export const SITE_TAGLINE = 'Live online professional training'

/** Default site description — R2-conservative wording (CLAUDE.md §9). */
export const SITE_DESCRIPTION =
  'Expert-led live courses that prepare you for ISO/IEC 42001:2023, taught one-to-one on Zoom.'

/** Site-wide default OG image (1200×630, generated by scripts/generate-og.ts). */
export const DEFAULT_OG_IMAGE = '/og-default.png'

/** Canonical site origin, without a trailing slash. */
export const getSiteUrl = (): string =>
  (process.env.NEXT_PUBLIC_SITE_URL?.trim() || 'http://localhost:3000').replace(/\/+$/, '')

/** Prefix a site-relative path with the canonical origin. */
export const absoluteUrl = (path: string): string =>
  `${getSiteUrl()}${path.startsWith('/') ? path : `/${path}`}`
