// Verbatim content of the "cookies" legal page (EN + RO).
// Source: 'cookies EN.docx' and 'cookies RO.docx'. Do not edit by hand — legal copy.

type Block = { type: 'p'; text: string } | { type: 'ul'; items: string[] }
type Section = { heading: string; blocks: Block[] }
type Content = { title: string; intro: string; sections: Section[] }

const cookies: { en: Content; ro: Content } = {
  en: {
    title: 'COOKIE POLICY',
    intro: '(hereinafter referred to as the “Cookie Policy”)',
    sections: [
      {
        heading: '1. Introduction',
        blocks: [
          { type: 'p', text: 'This Cookie Policy explains how INTERNATIONAL SECURITY AND DEFENCE S.R.L., the operator of the ISAD.academy platform, uses cookies and similar technologies on the website https://isad.academy (hereinafter referred to as the “Platform” or “Site”).' },
          { type: 'p', text: 'This Policy supplements the Privacy Policy and the Terms and Conditions of Use of the ISAD.academy Platform and should be read in conjunction with them.' },
          { type: 'p', text: 'By using the Platform, users may be exposed to cookies that are strictly necessary for the Site’s operation; for other categories of cookies, consent is requested via the cookie banner, in accordance with applicable law.' },
        ],
      },
      {
        heading: '2. Data Controller',
        blocks: [
          { type: 'p', text: 'The data controller is:' },
          { type: 'p', text: 'INTERNATIONAL SECURITY AND DEFENCE S.R.L.' },
          { type: 'p', text: 'Website:' },
          { type: 'p', text: 'https://isad.academy' },
          { type: 'p', text: 'Email:' },
          { type: 'p', text: 'support@isad.academy' },
        ],
      },
      {
        heading: '3. What Are Cookies?',
        blocks: [
          { type: 'p', text: 'A cookie is a small file consisting of letters and numbers that is stored on the user’s device (computer, mobile phone, tablet, or other device) when the user visits a website.' },
          { type: 'p', text: 'Cookies allow the user’s device to be recognized and facilitate the Platform’s operation, improve the user experience, remember preferences, and provide statistical information regarding the use of the Site.' },
          { type: 'p', text: 'Cookies do not contain software and cannot access information stored on the user’s device beyond the data required for their operation.' },
        ],
      },
      {
        heading: '4. Similar Technologies',
        blocks: [
          { type: 'p', text: 'In addition to cookies, ISAD.academy may also use other similar technologies, such as:' },
          { type: 'ul', items: [
            'Local Storage;',
            'Session Storage;',
            'Pixel Tags;',
            'Web Beacons;',
            'App SDKs;',
            'anonymous identifiers;',
            'traffic analysis technologies.',
          ] },
          { type: 'p', text: 'For the purposes of this Policy, all of these technologies are collectively referred to as “Cookies.”' },
        ],
      },
      {
        heading: '5. Types of Cookies Used',
        blocks: [
          { type: 'p', text: 'ISAD.academy may use the following categories of Cookies.' },
          { type: 'p', text: '5.1 Strictly Necessary Cookies' },
          { type: 'p', text: 'These Cookies are essential for the Platform to function.' },
          { type: 'p', text: 'They enable:' },
          { type: 'ul', items: [
            'user authentication;',
            'securing sessions;',
            'account access;',
            'order completion;',
            'the operation of the LMS Platform;',
            'protection against cyberattacks;',
            'server load balancing.',
          ] },
          { type: 'p', text: 'These cookies cannot be disabled in the preferences panel, as the Platform cannot function properly without them.' },
          { type: 'p', text: '5.2 Functional Cookies' },
          { type: 'p', text: 'These cookies allow us to remember the user’s preferences.' },
          { type: 'p', text: 'For example:' },
          { type: 'ul', items: [
            'the selected language;',
            'the Platform’s theme;',
            'time zone;',
            'display preferences;',
            'recently viewed courses;',
            'notification preferences.',
          ] },
          { type: 'p', text: '5.3 Analytics Cookies' },
          { type: 'p', text: 'These cookies help us understand how users interact with the Platform.' },
          { type: 'p', text: 'They may collect information such as:' },
          { type: 'ul', items: [
            'the number of visitors;',
            'pages visited;',
            'session duration;',
            'bounce rate;',
            'traffic source;',
            'page performance.',
          ] },
          { type: 'p', text: 'This information is used exclusively to improve ISAD.academy’s services.' },
          { type: 'p', text: '5.4 Performance Cookies' },
          { type: 'p', text: 'These cookies help optimize the Site’s performance.' },
          { type: 'p', text: 'They may be used to:' },
          { type: 'ul', items: [
            'reduce loading time;',
            'detect errors;',
            'monitoring server performance;',
            'optimizing resources.',
          ] },
          { type: 'p', text: '5.5 Marketing Cookies' },
          { type: 'p', text: 'These cookies may be used to:' },
          { type: 'ul', items: [
            'displaying relevant ads;',
            'measuring campaign effectiveness;',
            'limiting the number of times an ad is displayed;',
            'remarketing;',
            'personalizing marketing communications.',
          ] },
          { type: 'p', text: 'These cookies are installed only with the user’s consent, when required by applicable law.' },
        ],
      },
      {
        heading: '6. Third-Party Cookies',
        blocks: [
          { type: 'p', text: 'ISAD.academy may use services provided by third parties, which may install their own cookies on the user’s device.' },
          { type: 'p', text: 'Depending on the features implemented on the Platform, these providers may include, but are not limited to:' },
          { type: 'ul', items: [
            'Google;',
            'Google Analytics;',
            'Google Tag Manager;',
            'Google Ads;',
            'Microsoft Clarity;',
            'Microsoft Advertising;',
            'Meta (Facebook and Instagram);',
            'LinkedIn;',
            'YouTube;',
            'Vimeo;',
            'Zoom;',
            'Microsoft Teams;',
            'Stripe;',
            'PayPal;',
            'payment processors used by the Platform;',
            'LMS providers;',
            'CRM providers;',
            'other services integrated at a later date.',
          ] },
          { type: 'p', text: 'Each provider processes data in accordance with its own privacy policies, and ISAD.academy recommends reviewing them.' },
        ],
      },
      {
        heading: '7. Purposes of Using Cookies',
        blocks: [
          { type: 'p', text: 'Cookies may be used for:' },
          { type: 'ul', items: [
            'ensure the proper functioning of the Platform;',
            'user authentication;',
            'account security;',
            'storing preferences;',
            'analyzing traffic;',
            'improving the user experience;',
            'fraud prevention;',
            'protecting the Platform against unauthorized access;',
            'measuring performance;',
            'personalizing content;',
            'managing marketing campaigns;',
            'generating statistical reports.',
          ] },
        ],
      },
      {
        heading: '8. Managing Cookie Preferences',
        blocks: [
          { type: 'p', text: 'Upon first accessing the Platform, the user will have the option to:' },
          { type: 'ul', items: [
            'accept all cookies;',
            'reject optional cookies;',
            'customize preferences for each category of cookies.',
          ] },
          { type: 'p', text: 'Consent may be modified or withdrawn at any time through the cookie preference management panel available on the Platform.' },
        ],
      },
      {
        heading: '9. Disabling Cookies',
        blocks: [
          { type: 'p', text: 'Most browsers allow you to control cookies through their settings.' },
          { type: 'p', text: 'Users can:' },
          { type: 'ul', items: [
            'delete existing cookies;',
            'block the installation of cookies;',
            'receive notifications before cookies are installed;',
            'allow only certain categories of cookies.',
          ] },
          { type: 'p', text: 'Disabling strictly necessary cookies may affect the Platform’s functionality and the availability of certain services.' },
        ],
      },
      {
        heading: '10. List of Cookies Used',
        blocks: [
          { type: 'p', text: 'ISAD.academy uses cookies and similar technologies to the extent necessary for the operation, security, improvement, and personalization of the Platform.' },
          { type: 'p', text: 'Information regarding the cookies used can be accessed through the preference management tool available on the Platform.' },
          { type: 'p', text: 'This information may be updated periodically, depending on technical changes, the introduction of new features, the integration of third-party services, or changes to how the Platform operates.' },
          { type: 'p', text: 'ISAD.academy strives to ensure that information regarding the use of cookies is clear, accurate, and up-to-date.' },
        ],
      },
      {
        heading: '11. Changes to the Cookie Policy',
        blocks: [
          { type: 'p', text: 'ISAD.academy reserves the right to amend this Policy to reflect:' },
          { type: 'ul', items: [
            'changes in legislation;',
            'technological changes;',
            'the introduction of new services;',
            'changes in service providers;',
            'changes to the categories of cookies used.',
          ] },
          { type: 'p', text: 'The updated version will be published on the Platform and will take effect as of the date of publication.' },
        ],
      },
      {
        heading: '12. Contact',
        blocks: [
          { type: 'p', text: 'For any questions regarding the use of cookies or the exercise of your rights under applicable law, please contact us at:' },
          { type: 'p', text: 'INTERNATIONAL SECURITY AND DEFENCE S.R.L.' },
          { type: 'p', text: 'Website: https://isad.academy' },
          { type: 'p', text: 'Email: support@isad.academy' },
        ],
      },
    ],
  },
  ro: {
    title: 'POLITICA PRIVIND MODULELE COOKIE',
    intro: '(denumită în continuare „Politica Cookie”)',
    sections: [
      {
        heading: '1. Introducere',
        blocks: [
          { type: 'p', text: 'Prezenta Politică privind modulele Cookie explică modul în care INTERNATIONAL SECURITY AND DEFENCE S.R.L., operatorul platformei ISAD.academy, utilizează module cookie și tehnologii similare pe website-ul https://isad.academy (denumit în continuare „Platforma” sau „Site-ul”).' },
          { type: 'p', text: 'Această Politică completează Politica de Confidențialitate și Termenii și Condițiile de Utilizare ale Platformei ISAD.academy și trebuie citită împreună cu acestea.' },
          { type: 'p', text: 'Prin utilizarea Platformei, utilizatorii pot fi expuși utilizării modulelor cookie strict necesare funcționării Site-ului, iar pentru celelalte categorii de cookie-uri consimțământul este solicitat prin intermediul bannerului de cookie-uri, în conformitate cu legislația aplicabilă.' },
        ],
      },
      {
        heading: '2. Operatorul',
        blocks: [
          { type: 'p', text: 'Operatorul datelor este:' },
          { type: 'p', text: 'INTERNATIONAL SECURITY AND DEFENCE S.R.L.' },
          { type: 'p', text: 'Website:' },
          { type: 'p', text: 'https://isad.academy' },
          { type: 'p', text: 'E-mail:' },
          { type: 'p', text: 'support@isad.academy' },
        ],
      },
      {
        heading: '3. Ce sunt modulele Cookie',
        blocks: [
          { type: 'p', text: 'Un modul cookie este un fișier de mici dimensiuni, format din litere și cifre, care este stocat pe dispozitivul utilizatorului (computer, telefon mobil, tabletă sau alt echipament) atunci când acesta accesează un website.' },
          { type: 'p', text: 'Cookie-urile permit recunoașterea dispozitivului utilizatorului și facilitează funcționarea Platformei, îmbunătățirea experienței de utilizare, memorarea preferințelor și furnizarea unor informații statistice privind utilizarea Site-ului.' },
          { type: 'p', text: 'Cookie-urile nu conțin programe software și nu pot accesa informațiile stocate pe dispozitivul utilizatorului în afara datelor prevăzute prin funcționarea lor.' },
        ],
      },
      {
        heading: '4. Tehnologii similare',
        blocks: [
          { type: 'p', text: 'Pe lângă modulele cookie, ISAD.academy poate utiliza și alte tehnologii similare, precum:' },
          { type: 'ul', items: [
            'Local Storage;',
            'Session Storage;',
            'Pixel Tags;',
            'Web Beacons;',
            'SDK-uri pentru aplicații;',
            'identificatori anonimi;',
            'tehnologii de analiză a traficului.',
          ] },
          { type: 'p', text: 'În cadrul prezentei Politici, toate aceste tehnologii sunt denumite în mod generic „Cookie-uri”.' },
        ],
      },
      {
        heading: '5. Tipurile de Cookie-uri utilizate',
        blocks: [
          { type: 'p', text: 'ISAD.academy poate utiliza următoarele categorii de Cookie-uri.' },
          { type: 'p', text: '5.1 Cookie-uri strict necesare' },
          { type: 'p', text: 'Aceste Cookie-uri sunt indispensabile funcționării Platformei.' },
          { type: 'p', text: 'Ele permit:' },
          { type: 'ul', items: [
            'autentificarea utilizatorilor;',
            'securizarea sesiunilor;',
            'accesul la cont;',
            'finalizarea comenzilor;',
            'funcționarea Platformei LMS;',
            'protecția împotriva atacurilor informatice;',
            'echilibrarea încărcării serverelor.',
          ] },
          { type: 'p', text: 'Aceste Cookie-uri nu pot fi dezactivate din panoul de preferințe, deoarece fără ele Platforma nu poate funcționa corespunzător.' },
          { type: 'p', text: '5.2 Cookie-uri funcționale' },
          { type: 'p', text: 'Aceste Cookie-uri permit memorarea preferințelor utilizatorului.' },
          { type: 'p', text: 'De exemplu:' },
          { type: 'ul', items: [
            'limba selectată;',
            'tema Platformei;',
            'fusul orar;',
            'preferințele privind afișarea;',
            'ultimele cursuri accesate;',
            'preferințele privind notificările.',
          ] },
          { type: 'p', text: '5.3 Cookie-uri de analiză' },
          { type: 'p', text: 'Aceste Cookie-uri permit înțelegerea modului în care utilizatorii utilizează Platforma.' },
          { type: 'p', text: 'Ele pot colecta informații precum:' },
          { type: 'ul', items: [
            'numărul vizitatorilor;',
            'paginile accesate;',
            'durata sesiunii;',
            'rata de abandon;',
            'sursa traficului;',
            'performanța paginilor.',
          ] },
          { type: 'p', text: 'Aceste informații sunt utilizate exclusiv pentru îmbunătățirea serviciilor ISAD.academy.' },
          { type: 'p', text: '5.4 Cookie-uri de performanță' },
          { type: 'p', text: 'Aceste Cookie-uri permit optimizarea funcționării Site-ului.' },
          { type: 'p', text: 'Ele pot fi utilizate pentru:' },
          { type: 'ul', items: [
            'reducerea timpului de încărcare;',
            'detectarea erorilor;',
            'monitorizarea performanței serverelor;',
            'optimizarea resurselor.',
          ] },
          { type: 'p', text: '5.5 Cookie-uri de marketing' },
          { type: 'p', text: 'Aceste Cookie-uri pot fi utilizate pentru:' },
          { type: 'ul', items: [
            'afișarea reclamelor relevante;',
            'măsurarea eficienței campaniilor;',
            'limitarea numărului de afișări ale unei reclame;',
            'remarketing;',
            'personalizarea comunicărilor comerciale.',
          ] },
          { type: 'p', text: 'Aceste Cookie-uri sunt instalate numai în baza consimțământului utilizatorului, atunci când legislația aplicabilă impune acest lucru.' },
        ],
      },
      {
        heading: '6. Cookie-uri ale terților',
        blocks: [
          { type: 'p', text: 'ISAD.academy poate utiliza servicii furnizate de terți, care pot instala propriile Cookie-uri pe dispozitivul utilizatorului.' },
          { type: 'p', text: 'În funcție de funcționalitățile implementate pe Platformă, acești furnizori pot include, fără a se limita la:' },
          { type: 'ul', items: [
            'Google;',
            'Google Analytics;',
            'Google Tag Manager;',
            'Google Ads;',
            'Microsoft Clarity;',
            'Microsoft Advertising;',
            'Meta (Facebook și Instagram);',
            'LinkedIn;',
            'YouTube;',
            'Vimeo;',
            'Zoom;',
            'Microsoft Teams;',
            'Stripe;',
            'PayPal;',
            'procesatori de plăți utilizați de Platformă;',
            'furnizori LMS;',
            'furnizori CRM;',
            'alte servicii integrate ulterior.',
          ] },
          { type: 'p', text: 'Fiecare furnizor prelucrează datele conform propriilor politici de confidențialitate, iar ISAD.academy recomandă consultarea acestora.' },
        ],
      },
      {
        heading: '7. Scopurile utilizării Cookie-urilor',
        blocks: [
          { type: 'p', text: 'Cookie-urile pot fi utilizate pentru:' },
          { type: 'ul', items: [
            'funcționarea corectă a Platformei;',
            'autentificarea utilizatorilor;',
            'securitatea conturilor;',
            'memorarea preferințelor;',
            'analiza traficului;',
            'îmbunătățirea experienței utilizatorilor;',
            'prevenirea fraudelor;',
            'protejarea Platformei împotriva accesului neautorizat;',
            'măsurarea performanței;',
            'personalizarea conținutului;',
            'administrarea campaniilor de marketing;',
            'generarea rapoartelor statistice.',
          ] },
        ],
      },
      {
        heading: '8. Gestionarea preferințelor privind Cookie-urile',
        blocks: [
          { type: 'p', text: 'La prima accesare a Platformei, utilizatorul va avea posibilitatea de a:' },
          { type: 'ul', items: [
            'accepta toate Cookie-urile;',
            'respinge Cookie-urile opționale;',
            'personaliza preferințele privind fiecare categorie de Cookie-uri.',
          ] },
          { type: 'p', text: 'Consimțământul poate fi modificat sau retras în orice moment prin intermediul panoului de administrare a preferințelor privind Cookie-urile disponibil pe Platformă.' },
        ],
      },
      {
        heading: '9. Dezactivarea Cookie-urilor',
        blocks: [
          { type: 'p', text: 'Majoritatea browserelor permit controlul Cookie-urilor prin intermediul setărilor proprii.' },
          { type: 'p', text: 'Utilizatorii pot:' },
          { type: 'ul', items: [
            'șterge Cookie-urile existente;',
            'bloca instalarea Cookie-urilor;',
            'primi notificări înainte de instalarea acestora;',
            'permite doar anumite categorii de Cookie-uri.',
          ] },
          { type: 'p', text: 'Dezactivarea Cookie-urilor strict necesare poate afecta funcționarea Platformei și disponibilitatea anumitor servicii.' },
        ],
      },
      {
        heading: '10. Lista Cookie-urilor utilizate',
        blocks: [
          { type: 'p', text: 'ISAD.academy utilizează module Cookie și tehnologii similare în măsura necesară pentru funcționarea, securizarea, îmbunătățirea și personalizarea Platformei.' },
          { type: 'p', text: 'Informațiile privind modulele Cookie utilizate pot fi consultate prin intermediul mecanismului de administrare a preferințelor disponibil pe Platformă.' },
          { type: 'p', text: 'Aceste informații pot fi actualizate periodic, în funcție de modificările tehnice, de introducerea unor funcționalități noi, de integrarea unor servicii furnizate de terți sau de schimbarea modului de funcționare a Platformei.' },
          { type: 'p', text: 'ISAD.academy depune eforturi pentru ca informațiile privind utilizarea modulelor Cookie să fie clare, corecte și actualizate.' },
        ],
      },
      {
        heading: '11. Modificarea Politicii Cookie',
        blocks: [
          { type: 'p', text: 'ISAD.academy își rezervă dreptul de a modifica prezenta Politică pentru a reflecta:' },
          { type: 'ul', items: [
            'modificări legislative;',
            'modificări tehnologice;',
            'introducerea unor servicii noi;',
            'schimbarea furnizorilor;',
            'modificarea categoriilor de Cookie-uri utilizate.',
          ] },
          { type: 'p', text: 'Versiunea actualizată va fi publicată pe Platformă și va produce efecte de la data publicării.' },
        ],
      },
      {
        heading: '12. Contact',
        blocks: [
          { type: 'p', text: 'Pentru orice întrebări privind utilizarea Cookie-urilor sau exercitarea drepturilor prevăzute de legislația aplicabilă, ne puteți contacta la:' },
          { type: 'p', text: 'INTERNATIONAL SECURITY AND DEFENCE S.R.L.' },
          { type: 'p', text: 'Website: https://isad.academy' },
          { type: 'p', text: 'E-mail: support@isad.academy' },
        ],
      },
    ],
  },
}

export default cookies
