type Block = { type: 'p'; text: string } | { type: 'ul'; items: string[] }
type Section = { heading: string; blocks: Block[] }
type Content = { title: string; intro: string; sections: Section[] }

const privacy: { en: Content; ro: Content } = {
  en: {
    title: 'ISAD.academy PRIVACY POLICY',
    intro: '',
    sections: [
      {
        heading: '1. General Information',
        blocks: [
          { type: 'p', text: 'This Privacy Policy sets forth how INTERNATIONAL SECURITY AND DEFENCE S.R.L., as a personal data controller, collects, uses, stores, discloses, and protects the personal data of users of the ISAD.academy, as well as the rights of data subjects in accordance with Regulation (EU) 2016/679 on the protection of natural persons with regard to the processing of personal data (“GDPR”), Law No. 190/2018, and other applicable laws and regulations.' },
          { type: 'p', text: 'This Policy is a separate document from the Platform’s Terms and Conditions and applies to all users who access the Site, create an account, request information, participate in courses, webinars, or conferences, or use any service available through the Platform.' },
          { type: 'p', text: 'The data controller is:' },
          { type: 'p', text: 'INTERNATIONAL SECURITY AND DEFENCE S.R.L.' },
          { type: 'p', text: 'hereinafter referred to as “ISAD.academy,” “the Controller,” “the Company,” or “we.”' },
          { type: 'p', text: 'Website:' },
          { type: 'p', text: 'https://isad.academy' },
          { type: 'p', text: 'For any questions regarding the processing of personal data, you may contact us at:' },
          { type: 'p', text: 'support@isad.academy' },
        ],
      },
      {
        heading: '2. Scope',
        blocks: [
          { type: 'p', text: 'This Policy applies to all individuals whose data is processed by ISAD.academy, including:' },
          { type: 'ul', items: [
            'website visitors;',
            'people who fill out forms;',
            'students;',
            'webinar participants;',
            'conference attendees;',
            'workshop participants;',
            'mentoring session participants;',
            'newsletter subscribers;',
            'members of ISAD communities;',
            'representatives of partner companies;',
            'collaborators;',
            'lecturers;',
            'mentors;',
            'speakers;',
            'suppliers;',
            'other individuals who interact with the Platform.',
          ] },
          { type: 'p', text: 'This Policy applies regardless of whether access to the services is free or for a fee.' },
        ],
      },
      {
        heading: '3. Definitions',
        blocks: [
          { type: 'p', text: 'For the purposes of this Policy:' },
          { type: 'p', text: 'Personal data means any information relating to an identified or identifiable natural person.' },
          { type: 'p', text: 'Processing means any operation performed on personal data, including the collection, recording, organization, structuring, storage, modification, consultation, use, transmission, restriction, or erasure thereof.' },
          { type: 'p', text: 'Data subject means the person whose data is being processed.' },
          { type: 'p', text: 'The Platform refers to the ISAD.academy website and all digital services made available through it.' },
          { type: 'p', text: 'LMS (Learning Management System) is the online platform used to deliver courses, manage users, assess progress, and issue certificates.' },
          { type: 'p', text: 'Services refer to all educational and professional services provided by ISAD.academy.' },
        ],
      },
      {
        heading: '4. Principles of Data Processing',
        blocks: [
          { type: 'p', text: 'ISAD.academy processes personal data in accordance with the principles set forth in the GDPR.' },
          { type: 'p', text: 'Thus, data is:' },
          { type: 'ul', items: [
            'processed lawfully, fairly, and transparently;',
            'collected for specified, explicit, and legitimate purposes;',
            'adequate, relevant, and limited to what is necessary;',
            'accurate and up-to-date;',
            'retained only for as long as necessary;',
            'protected against unauthorized access;',
            'processed in a manner that ensures their integrity and confidentiality.',
          ] },
          { type: 'p', text: 'The controller applies the principle of accountability and is able to demonstrate compliance with all obligations imposed by applicable law.' },
        ],
      },
      {
        heading: '5. Categories of Data Subjects',
        blocks: [
          { type: 'p', text: 'ISAD.academy may process data belonging to the following categories of individuals:' },
          { type: 'ul', items: [
            'website users;',
            'students;',
            'graduates;',
            'certification candidates;',
            'conference attendees;',
            'workshop participants;',
            'participants in online sessions;',
            'newsletter subscribers;',
            'representatives of legal entities;',
            'collaborators;',
            'lecturers;',
            'mentors;',
            'speakers;',
            'suppliers;',
            'people who request information via the contact form;',
            'people who file complaints;',
            'people who participate in promotional campaigns.',
          ] },
        ],
      },
      {
        heading: '6. What personal data do we collect?',
        blocks: [
          { type: 'p', text: 'Depending on the services you use, we may collect the following categories of data:' },
          { type: 'p', text: 'Identification data' },
          { type: 'ul', items: [
            'last name;',
            'first name;',
            'profile photo (optional);',
            'date of birth (if required for certifications).',
          ] },
          { type: 'p', text: 'Contact Information' },
          { type: 'ul', items: [
            'email address;',
            'phone number;',
            'mailing address;',
            'country;',
            'city.',
          ] },
          { type: 'p', text: 'Professional information' },
          { type: 'ul', items: [
            'employer;',
            'job title;',
            'field of work;',
            'level of experience;',
            'professional certifications;',
            'LinkedIn profile (if voluntarily provided).',
          ] },
          { type: 'p', text: 'Account information' },
          { type: 'ul', items: [
            'username;',
            'encrypted password;',
            'login history;',
            'activity log;',
            'IP address;',
            'device used.',
          ] },
          { type: 'p', text: 'Course information' },
          { type: 'ul', items: [
            'courses purchased;',
            'progress in the courses;',
            'test results;',
            'projects uploaded;',
            'grades earned;',
            'graduation status;',
            'certificates issued;',
            'digital badges.',
          ] },
          { type: 'p', text: 'Financial Data' },
          { type: 'p', text: 'ISAD.academy does not store full bank card details.' },
          { type: 'p', text: 'The following may be processed:' },
          { type: 'ul', items: [
            'order history;',
            'payment amounts;',
            'currency;',
            'payment method;',
            'transaction ID;',
            'payment status;',
            'invoice issued.',
          ] },
          { type: 'p', text: 'All payments are processed through authorized payment processors.' },
        ],
      },
      {
        heading: '7. How We Collect Personal Data',
        blocks: [
          { type: 'p', text: 'ISAD.academy collects personal data directly from data subjects or indirectly through the systems and services used to provide educational and professional services.' },
          { type: 'p', text: 'Data may be collected through:' },
          { type: 'ul', items: [
            'visiting the website;',
            'creating a user account;',
            'filling out registration forms;',
            'purchasing courses or services;',
            'participating in online or in-person courses;',
            'participating in conferences, workshops, and webinars;',
            'communicating via email;',
            'communicating by phone;',
            'communication via WhatsApp, Microsoft Teams, Zoom, or other platforms used to conduct activities;',
            'participation in ISAD.academy communities;',
            'submitting the documents required for certification;',
            'completing feedback questionnaires;',
            'using the LMS platform;',
            'interacting with official social media pages;',
            'using cookies and similar technologies.',
          ] },
          { type: 'p', text: 'Data may be collected both before the start of the contractual relationship and throughout its duration, as well as afterward, within the limits provided by law.' },
        ],
      },
      {
        heading: '8. Data Collected Through the Website',
        blocks: [
          { type: 'p', text: 'When you access the ISAD.academy website, certain technical information necessary for the operation and security of the Platform may be collected automatically.' },
          { type: 'p', text: 'This information may include:' },
          { type: 'ul', items: [
            'IP address;',
            'browser type and version;',
            'operating system used;',
            'device type;',
            'screen resolution;',
            'browser language;',
            'time zone;',
            'date and time of access;',
            'pages visited;',
            'session duration;',
            'referrer;',
            'session identifiers;',
            'information regarding website performance;',
            'technical errors generated during use.',
          ] },
          { type: 'p', text: 'This information is used for:' },
          { type: 'ul', items: [
            'administer the website;',
            'improving the Platform’s performance;',
            'identifying security incidents;',
            'preventing fraud;',
            'statistical analysis;',
            'optimizing the user experience.',
          ] },
          { type: 'p', text: 'To the extent that this information allows for the identification of an individual, it is considered personal data and is processed in accordance with this Policy.' },
        ],
      },
      {
        heading: '9. Data Collected Through the LMS Platform',
        blocks: [
          { type: 'p', text: 'The LMS Platform used by ISAD.academy may automatically record user activity for the purpose of providing educational services.' },
          { type: 'p', text: 'The following data may be collected, including but not limited to:' },
          { type: 'ul', items: [
            'the login date;',
            'login time;',
            'session duration;',
            'course access history;',
            'modules completed;',
            'percentage of progress;',
            'downloaded materials;',
            'videos watched;',
            'test results;',
            'time spent on each lesson;',
            'projects uploaded;',
            'answers to assessments;',
            'certificates generated;',
            'certification history;',
            'digital badges awarded;',
            'activity within the Platform’s community.',
          ] },
          { type: 'p', text: 'This information allows for:' },
          { type: 'ul', items: [
            'monitoring educational progress;',
            'issuing certificates;',
            'resuming classes from the point where they were interrupted;',
            'providing access to additional resources;',
            'providing subscription-related benefits.',
          ] },
        ],
      },
      {
        heading: '10. Data Collected During Courses, Workshops, and Conferences',
        blocks: [
          { type: 'p', text: 'Depending on the nature of the event, ISAD.academy may collect the following categories of data:' },
          { type: 'ul', items: [
            'attendance at the event;',
            'signature on the attendance list;',
            'photos taken during the event;',
            'video recordings;',
            'audio recordings;',
            'questions asked of the speakers;',
            'assessment results;',
            'feedback provided;',
            'information regarding active participation.',
          ] },
          { type: 'p', text: 'This data is used for:' },
          { type: 'ul', items: [
            'organizing the event;',
            'issuing certificates;',
            'verifying participation;',
            'improving services;',
            'promoting ISAD.academy activities, if there is a legal basis for doing so.',
          ] },
        ],
      },
      {
        heading: '11. Payment and Billing Information',
        blocks: [
          { type: 'p', text: 'In order to provide the contracted services, ISAD.academy processes information regarding payments made.' },
          { type: 'p', text: 'This information may include:' },
          { type: 'ul', items: [
            'the payer’s name;',
            'billing address;',
            'tax ID number (for legal entities);',
            'company name;',
            'order history;',
            'amount paid;',
            'applicable VAT;',
            'transaction currency;',
            'payment method;',
            'transaction ID;',
            'payment status;',
            'refund history.',
          ] },
          { type: 'p', text: 'ISAD.academy does not store and does not have access to the full details of the bank cards used to make payments.' },
          { type: 'p', text: 'Payments are processed through authorized payment processors, which act as independent operators or authorized agents, depending on the existing contractual relationship.' },
          { type: 'p', text: 'To prevent fraud, ISAD.academy may verify certain transaction information and may temporarily suspend the provision of services if there are reasonable grounds to suspect fraudulent use of a payment method.' },
        ],
      },
      {
        heading: '12. Data Regarding Assessments and Certifications',
        blocks: [
          { type: 'p', text: 'For courses that involve assessment and the issuance of a certificate, ISAD.academy may process the following information:' },
          { type: 'ul', items: [
            'exam results;',
            'grades obtained;',
            'test answers;',
            'completed projects;',
            'evaluations conducted by instructors;',
            'date of graduation;',
            'certificate series;',
            'certificate number;',
            'date of issuance;',
            'certificate history.',
          ] },
          { type: 'p', text: 'This data is used exclusively for:' },
          { type: 'ul', items: [
            'skills assessment;',
            'issuing certificates;',
            'verifying the authenticity of certificates;',
            'preventing document forgery;',
            'fulfilling legal or contractual obligations.',
          ] },
        ],
      },
      {
        heading: '13. Audio, Video, and Photographic Recordings',
        blocks: [
          { type: 'p', text: 'During certain courses, workshops, conferences, or events organized by ISAD.academy, photographs, audio recordings, or video recordings may be made.' },
          { type: 'p', text: 'These recordings may serve the following purposes:' },
          { type: 'ul', items: [
            'conducting educational activities;',
            'to allow participants to access the content later;',
            'creating supporting materials;',
            'documenting events;',
            'promoting ISAD.academy activities;',
            'improving the quality of services.',
          ] },
          { type: 'p', text: 'When the use of images for promotional purposes requires the consent of the data subject, such consent will be requested separately, in accordance with the requirements of applicable law.' },
          { type: 'p', text: 'Participants are informed prior to the start of the event regarding the existence of any audio-visual recordings.' },
        ],
      },
      {
        heading: '14. Purposes of Personal Data Processing',
        blocks: [
          { type: 'p', text: 'ISAD.academy processes personal data exclusively for specific, explicit, and legitimate purposes, in accordance with the provisions of Regulation (EU) 2016/679 (GDPR) and applicable national legislation.' },
          { type: 'p', text: 'Personal data may be processed, as applicable, for the following purposes:' },
          { type: 'p', text: 'a) creating and managing the user account;' },
          { type: 'p', text: 'b) providing access to the Platform and educational services;' },
          { type: 'p', text: 'c) registration for courses, webinars, workshops, conferences, and other events;' },
          { type: 'p', text: 'd) managing subscriptions and service packages;' },
          { type: 'p', text: 'e) issuing certificates of participation or completion;' },
          { type: 'p', text: 'f) assessing educational progress and administering exams;' },
          { type: 'p', text: 'g) communicating with users regarding contracted services;' },
          { type: 'p', text: 'h) processing orders and issuing tax documents;' },
          { type: 'p', text: 'i) handling requests, complaints, and reports;' },
          { type: 'p', text: 'j) providing technical support;' },
          { type: 'p', text: 'k) managing the ISAD.academy communities;' },
          { type: 'p', text: 'l) organizing mentoring sessions;' },
          { type: 'p', text: 'm) preventing fraud and protecting the Platform against unauthorized access;' },
          { type: 'p', text: 'n) ensuring information security;' },
          { type: 'p', text: 'o) compliance with legal obligations;' },
          { type: 'p', text: 'p) improving the services provided;' },
          { type: 'p', text: 'q) conducting statistical and operational analyses;' },
          { type: 'p', text: 'r) conducting marketing campaigns, in accordance with the law;' },
          { type: 'p', text: 's) exercising or defending rights in court;' },
          { type: 'p', text: 't) any other purposes compatible with those listed above, as permitted by applicable law.' },
        ],
      },
      {
        heading: '15. Legal Bases for Processing',
        blocks: [
          { type: 'p', text: 'ISAD.academy processes personal data only to the extent that there is a legal basis provided for in Article 6 of the GDPR.' },
          { type: 'p', text: 'Depending on the situation, processing may be based on one or more of the following grounds:' },
          { type: 'p', text: '15.1 Performance of a contract' },
          { type: 'p', text: 'Data is processed when necessary to:' },
          { type: 'ul', items: [
            'providing access to the Platform;',
            'managing the account;',
            'delivering courses;',
            'organizing events;',
            'issuing certificates;',
            'providing mentorship;',
            'granting access to resources;',
            'processing payments;',
            'issuing invoices.',
          ] },
          { type: 'p', text: '15.2 Compliance with Legal Obligations' },
          { type: 'p', text: 'ISAD.academy may process data to comply with obligations imposed by legislation regarding:' },
          { type: 'ul', items: [
            'accounting;',
            'taxation;',
            'document archiving;',
            'fraud prevention;',
            'combating cybercrime;',
            'consumer protection;',
            'computer network security;',
            'other obligations provided for by applicable law.',
          ] },
          { type: 'p', text: '15.3 Legitimate Interest' },
          { type: 'p', text: 'The controller may process data when this is necessary for its legitimate interests, without infringing upon the fundamental rights and freedoms of the data subjects.' },
          { type: 'p', text: 'These interests may include:' },
          { type: 'ul', items: [
            'developing the Platform;',
            'improving the user experience;',
            'preventing fraudulent use of accounts;',
            'the security of information systems;',
            'internal auditing;',
            'monitoring the Platform’s operation;',
            'defending rights in court;',
            'preventing unauthorized access;',
            'detection of fraud attempts;',
            'conducting statistical analyses;',
            'measuring service performance.',
          ] },
          { type: 'p', text: '15.4 Consent' },
          { type: 'p', text: 'In situations where the law requires consent, ISAD.academy will request the data subject’s express consent.' },
          { type: 'p', text: 'This may be necessary, for example, for:' },
          { type: 'ul', items: [
            'sending newsletters;',
            'commercial communications;',
            'the use of non-essential cookies;',
            'publishing photos for promotional purposes;',
            'the use of testimonials;',
            'participation in promotional campaigns.',
          ] },
          { type: 'p', text: 'Consent may be withdrawn at any time, without affecting the lawfulness of processing carried out prior to its withdrawal.' },
        ],
      },
      {
        heading: '16. Commercial and Marketing Communications',
        blocks: [
          { type: 'p', text: 'ISAD.academy may send information regarding:' },
          { type: 'ul', items: [
            'the launch of new courses;',
            'conferences;',
            'webinars;',
            'workshops;',
            'events;',
            'discounts;',
            'special offers;',
            'educational programs;',
            'updates regarding the Platform;',
            'articles and educational resources.',
          ] },
          { type: 'p', text: 'These communications will be sent only:' },
          { type: 'ul', items: [
            'based on the data subject’s consent; or',
            'based on legitimate interest, in cases permitted by law.',
          ] },
          { type: 'p', text: 'Each electronic marketing communication will include a quick and free option to unsubscribe.' },
          { type: 'p', text: 'The unsubscribe request will take effect without undue delay.' },
        ],
      },
      {
        heading: '17. Use of Artificial Intelligence-Based Tools',
        blocks: [
          { type: 'p', text: 'To improve the educational experience and streamline services, ISAD.academy may use tools based on artificial intelligence (“AI”).' },
          { type: 'p', text: 'These tools may be used to:' },
          { type: 'ul', items: [
            'generating educational content;',
            'assisting in the learning process;',
            'providing automated responses to user questions;',
            'translating materials;',
            'generating examples and exercises;',
            'organizing information;',
            'automation of administrative processes.',
          ] },
          { type: 'p', text: 'ISAD.academy does not use AI systems to make fully automated decisions that produce legal effects on data subjects, except in cases permitted by applicable law.' },
          { type: 'p', text: 'The use of AI tools does not eliminate human intervention in the relevant processes and does not replace the Controller’s responsibility to respect the rights of data subjects.' },
        ],
      },
      {
        heading: '18. Cookies and Similar Technologies',
        blocks: [
          { type: 'p', text: 'The ISAD.academy website uses cookies and similar technologies to:' },
          { type: 'ul', items: [
            'the operation of the Platform;',
            'authenticate users;',
            'storing preferences;',
            'analyze traffic;',
            'measuring performance;',
            'content personalization;',
            'service security.',
          ] },
          { type: 'p', text: 'Cookies are classified, as appropriate, into:' },
          { type: 'ul', items: [
            'strictly necessary cookies;',
            'functional cookies;',
            'analytics cookies;',
            'performance cookies;',
            'marketing cookies.',
          ] },
          { type: 'p', text: 'Full details regarding the use of cookies are provided in the Cookie Policy, a separate document.' },
        ],
      },
      {
        heading: '19. Profiling and Automated Processing',
        blocks: [
          { type: 'p', text: 'ISAD.academy may use limited automated processing for:' },
          { type: 'ul', items: [
            'recommending relevant courses;',
            'personalizing educational content;',
            'displaying progress;',
            'awarding badges;',
            'organizing available resources.',
          ] },
          { type: 'p', text: 'These activities do not produce legal effects and do not result in automated decisions regarding users’ rights.' },
          { type: 'p', text: 'Should automated processes falling under Article 22 of the GDPR be implemented in the future, users will be duly informed and will enjoy all rights provided by applicable law.' },
        ],
      },
      {
        heading: '20. Retention Period for Personal Data',
        blocks: [
          { type: 'p', text: 'ISAD.academy retains personal data only for as long as necessary to fulfill the purposes for which it was collected, as well as to comply with applicable legal obligations.' },
          { type: 'p', text: 'The retention period may vary depending on the category of data and the legal basis for processing.' },
          { type: 'p', text: 'As a general guideline:' },
          { type: 'p', text: 'Data Category' },
          { type: 'p', text: 'Retention Period' },
          { type: 'p', text: 'User account data' },
          { type: 'p', text: 'For the duration of the account’s existence and up to 3 years after its closure' },
          { type: 'p', text: 'Order and invoice data' },
          { type: 'p', text: 'in accordance with applicable tax and accounting laws' },
          { type: 'p', text: 'Data regarding issued certificates' },
          { type: 'p', text: 'for the period necessary to verify their authenticity and for archiving purposes' },
          { type: 'p', text: 'Data regarding course participation' },
          { type: 'p', text: 'for the duration of the contractual relationship and thereafter, for the purpose of maintaining an educational history' },
          { type: 'p', text: 'Requests and complaints' },
          { type: 'p', text: 'until final resolution and thereafter in accordance with legal deadlines' },
          { type: 'p', text: 'Data used for marketing purposes' },
          { type: 'p', text: 'until consent is withdrawn or the right to object is exercised' },
          { type: 'p', text: 'Technical and security logs' },
          { type: 'p', text: 'as long as necessary for the security of the Platform and the investigation of incidents' },
          { type: 'p', text: 'Upon expiration of the retention periods, the data will be deleted, anonymized, or archived, as applicable, in accordance with legal obligations.' },
        ],
      },
      {
        heading: '21. Data Security',
        blocks: [
          { type: 'p', text: 'ISAD.academy implements appropriate technical and organizational measures to protect personal data against:' },
          { type: 'ul', items: [
            'unauthorized access;',
            'accidental or unlawful disclosure;',
            'unauthorized modification;',
            'destruction;',
            'loss;',
            'misuse.',
          ] },
          { type: 'p', text: 'These measures may include, but are not limited to:' },
          { type: 'ul', items: [
            'encrypting communications using secure protocols (SSL/TLS);',
            'user authentication;',
            'role-based access control;',
            'secure passwords stored in encrypted format;',
            'backups;',
            'infrastructure monitoring;',
            'regular updates to IT systems;',
            'antivirus and anti-malware protection;',
            'firewalls and mechanisms for detecting unauthorized access;',
            'periodic security audits.',
          ] },
          { type: 'p', text: 'Although we make every reasonable effort to protect your data, no IT system can guarantee absolute security.' },
        ],
      },
      {
        heading: '22. Recipients of Personal Data',
        blocks: [
          { type: 'p', text: 'Depending on the nature of the services provided, ISAD.academy may transfer personal data to the following categories of recipients:' },
          { type: 'ul', items: [
            'LMS platform providers;',
            'cloud service providers;',
            'payment processors;',
            'hosting service providers;',
            'IT service providers;',
            'email service providers;',
            'CRM service providers;',
            'videoconferencing service providers;',
            'analytics and monitoring service providers;',
            'legal consultants;',
            'tax and accounting consultants;',
            'auditors;',
            'public institutions and competent authorities, when there is a legal obligation to do so.',
          ] },
          { type: 'p', text: 'All service providers that process data on behalf of ISAD.academy are carefully selected and are contractually obligated to comply with GDPR requirements and appropriate security standards.' },
          { type: 'p', text: 'ISAD.academy does not sell or rent personal data to third parties.' },
        ],
      },
      {
        heading: '23. International Data Transfers',
        blocks: [
          { type: 'p', text: 'In certain situations, service providers used by ISAD.academy may store or process data outside the European Economic Area (EEA).' },
          { type: 'p', text: 'In such cases, transfers will only take place if the conditions set forth in Articles 44–49 of the GDPR are met, including through:' },
          { type: 'ul', items: [
            'adequacy decisions issued by the European Commission;',
            'Standard Contractual Clauses (SCCs);',
            'other appropriate safeguards provided for by applicable law.',
          ] },
          { type: 'p', text: 'ISAD.academy makes every effort to use service providers that offer an adequate level of protection for personal data.' },
        ],
      },
      {
        heading: '24. Rights of Data Subjects',
        blocks: [
          { type: 'p', text: 'In accordance with the GDPR, data subjects have the following rights:' },
          { type: 'ul', items: [
            'the right of access;',
            'the right to rectification;',
            'the right to erasure (“right to be forgotten”);',
            'the right to restriction of processing;',
            'the right to data portability;',
            'the right to object;',
            'the right not to be subject to a decision based solely on automated processing, including profiling;',
            'the right to withdraw consent;',
            'the right to lodge a complaint with the competent authority.',
          ] },
          { type: 'p', text: 'The exercise of these rights is free of charge, except in cases where the requests are manifestly unfounded or excessive, in accordance with legal provisions.' },
        ],
      },
      {
        heading: '25. Exercising Your Rights',
        blocks: [
          { type: 'p', text: 'Requests regarding the exercise of the rights set forth in this Policy may be submitted to:' },
          { type: 'p', text: 'Email: support@isad.academy' },
          { type: 'p', text: 'ISAD.academy will respond to requests without undue delay and, in any case, within the timeframe provided by applicable law.' },
          { type: 'p', text: 'In cases where there are reasonable doubts regarding the identity of the requester, the Controller may request additional information necessary to verify the identity.' },
        ],
      },
      {
        heading: '26. Supervisory Authority',
        blocks: [
          { type: 'p', text: 'If you believe that your data protection rights have been violated, you have the right to file a complaint with:' },
          { type: 'p', text: 'the National Supervisory Authority for the Processing of Personal Data (ANSPDCP)' },
          { type: 'p', text: 'You also have the right to bring a claim before the competent courts, in accordance with the law.' },
        ],
      },
      {
        heading: '27. Updates to the Privacy Policy',
        blocks: [
          { type: 'p', text: 'ISAD.academy reserves the right to amend this Policy whenever necessary, including as a result of:' },
          { type: 'ul', items: [
            'changes in legislation;',
            'changes to the services offered;',
            'the introduction of new features;',
            'changes to the providers or technologies used;',
            'the implementation of new information security requirements.',
          ] },
          { type: 'p', text: 'The updated version will be published on the website, and the date of the last update will be indicated in the introduction to the document.' },
          { type: 'p', text: 'Continued use of the Platform following the publication of the changes constitutes acceptance of those changes, to the extent permitted by applicable law.' },
        ],
      },
      {
        heading: '28. Contact Information',
        blocks: [
          { type: 'p', text: 'For any questions regarding this Privacy Policy or how ISAD.academy processes personal data, you may contact us at:' },
          { type: 'p', text: 'INTERNATIONAL SECURITY AND DEFENCE S.R.L.' },
          { type: 'p', text: 'Website: https://isad.academy' },
          { type: 'p', text: 'Email: support@isad.academy' },
        ],
      },
    ],
  },
  ro: {
    title: 'POLITICA DE CONFIDENȚIALITATE ISAD.academy',
    intro: '',
    sections: [
      {
        heading: '1. Informații generale',
        blocks: [
          { type: 'p', text: 'Prezenta Politică de Confidențialitate stabilește modul în care INTERNATIONAL SECURITY AND DEFENCE S.R.L., în calitate de operator de date cu caracter personal, colectează, utilizează, stochează, divulgă și protejează datele cu caracter personal ale utilizatorilor Platformei ISAD.academy, precum și drepturile persoanelor vizate în conformitate cu Regulamentul (UE) 2016/679 privind protecția persoanelor fizice în ceea ce privește prelucrarea datelor cu caracter personal („GDPR”), Legea nr. 190/2018 și celelalte acte normative aplicabile.' },
          { type: 'p', text: 'Prezenta Politică este un document distinct de Termenii și Condițiile Platformei și se aplică tuturor utilizatorilor care accesează Site-ul, își creează un cont, solicită informații, participă la cursuri, webinarii, conferințe sau utilizează orice serviciu disponibil prin intermediul Platformei.' },
          { type: 'p', text: 'Operatorul datelor este:' },
          { type: 'p', text: 'INTERNATIONAL SECURITY AND DEFENCE S.R.L.' },
          { type: 'p', text: 'denumită în continuare „ISAD.academy”, „Operatorul”, „Societatea” sau „noi”.' },
          { type: 'p', text: 'Website:' },
          { type: 'p', text: 'https://isad.academy' },
          { type: 'p', text: 'Pentru orice întrebări privind prelucrarea datelor personale, ne puteți contacta la:' },
          { type: 'p', text: 'support@isad.academy' },
        ],
      },
      {
        heading: '2. Domeniul de aplicare',
        blocks: [
          { type: 'p', text: 'Prezenta Politică se aplică tuturor persoanelor ale căror date sunt prelucrate de către ISAD.academy, inclusiv:' },
          { type: 'ul', items: [
            'vizitatori ai website-ului;',
            'persoane care completează formulare;',
            'cursanți;',
            'participanți la webinarii;',
            'participanți la conferințe;',
            'participanți la workshopuri;',
            'participanți la sesiuni de mentorat;',
            'persoane înscrise la newsletter;',
            'membri ai comunităților ISAD;',
            'reprezentanți ai companiilor partenere;',
            'colaboratori;',
            'lectori;',
            'mentori;',
            'speakeri;',
            'furnizori;',
            'alte persoane care interacționează cu Platforma.',
          ] },
          { type: 'p', text: 'Prezenta Politică se aplică indiferent dacă accesul la servicii este gratuit sau contra cost.' },
        ],
      },
      {
        heading: '3. Definiții',
        blocks: [
          { type: 'p', text: 'În sensul prezentei Politici:' },
          { type: 'p', text: 'Date cu caracter personal reprezintă orice informație privind o persoană fizică identificată sau identificabilă.' },
          { type: 'p', text: 'Prelucrare reprezintă orice operațiune efectuată asupra datelor personale, inclusiv colectarea, înregistrarea, organizarea, structurarea, stocarea, modificarea, consultarea, utilizarea, transmiterea, restricționarea sau ștergerea acestora.' },
          { type: 'p', text: 'Persoană vizată reprezintă persoana ale cărei date sunt prelucrate.' },
          { type: 'p', text: 'Platforma reprezintă website-ul ISAD.academy și toate serviciile digitale puse la dispoziție prin intermediul acestuia.' },
          { type: 'p', text: 'LMS (Learning Management System) reprezintă platforma electronică utilizată pentru desfășurarea cursurilor, administrarea utilizatorilor, evaluarea progresului și emiterea certificatelor.' },
          { type: 'p', text: 'Servicii reprezintă totalitatea serviciilor educaționale și profesionale furnizate de ISAD.academy.' },
        ],
      },
      {
        heading: '4. Principiile prelucrării datelor',
        blocks: [
          { type: 'p', text: 'ISAD.academy prelucrează datele personale în conformitate cu principiile prevăzute de GDPR.' },
          { type: 'p', text: 'Astfel, datele sunt:' },
          { type: 'ul', items: [
            'prelucrate în mod legal, echitabil și transparent;',
            'colectate în scopuri determinate, explicite și legitime;',
            'adecvate, relevante și limitate la ceea ce este necesar;',
            'exacte și actualizate;',
            'păstrate numai pe perioada necesară;',
            'protejate împotriva accesului neautorizat;',
            'prelucrate într-un mod care asigură integritatea și confidențialitatea acestora.',
          ] },
          { type: 'p', text: 'Operatorul aplică principiul responsabilității („accountability”), fiind în măsură să demonstreze respectarea tuturor obligațiilor impuse de legislația aplicabilă.' },
        ],
      },
      {
        heading: '5. Categoriile de persoane vizate',
        blocks: [
          { type: 'p', text: 'ISAD.academy poate prelucra date aparținând următoarelor categorii de persoane:' },
          { type: 'ul', items: [
            'utilizatori ai website-ului;',
            'cursanți;',
            'absolvenți;',
            'candidați la certificări;',
            'participanți la conferințe;',
            'participanți la workshopuri;',
            'participanți la sesiuni online;',
            'persoane înscrise la newsletter;',
            'reprezentanți ai persoanelor juridice;',
            'colaboratori;',
            'lectori;',
            'mentori;',
            'speakeri;',
            'furnizori;',
            'persoane care solicită informații prin formularul de contact;',
            'persoane care formulează reclamații;',
            'persoane care participă la campanii promoționale.',
          ] },
        ],
      },
      {
        heading: '6. Ce date cu caracter personal colectăm',
        blocks: [
          { type: 'p', text: 'În funcție de serviciile utilizate, putem colecta următoarele categorii de date:' },
          { type: 'p', text: 'Date de identificare' },
          { type: 'ul', items: [
            'nume;',
            'prenume;',
            'fotografie de profil (opțional);',
            'data nașterii (dacă este necesară pentru certificări).',
          ] },
          { type: 'p', text: 'Date de contact' },
          { type: 'ul', items: [
            'adresa de e-mail;',
            'număr de telefon;',
            'adresă poștală;',
            'țara;',
            'orașul.',
          ] },
          { type: 'p', text: 'Date profesionale' },
          { type: 'ul', items: [
            'angajator;',
            'funcție;',
            'domeniul de activitate;',
            'nivel de experiență;',
            'certificări profesionale;',
            'profil LinkedIn (dacă este furnizat voluntar).',
          ] },
          { type: 'p', text: 'Date privind contul' },
          { type: 'ul', items: [
            'username;',
            'parolă criptată;',
            'istoricul autentificărilor;',
            'jurnalul activităților;',
            'adresa IP;',
            'dispozitivul utilizat.',
          ] },
          { type: 'p', text: 'Date privind cursurile' },
          { type: 'ul', items: [
            'cursurile achiziționate;',
            'progresul în cadrul cursurilor;',
            'rezultatele testelor;',
            'proiectele încărcate;',
            'notele obținute;',
            'statusul absolvirii;',
            'certificatele emise;',
            'badge-urile digitale.',
          ] },
          { type: 'p', text: 'Date financiare' },
          { type: 'p', text: 'ISAD.academy nu stochează datele complete ale cardurilor bancare.' },
          { type: 'p', text: 'Pot fi prelucrate:' },
          { type: 'ul', items: [
            'istoricul comenzilor;',
            'valoarea plăților;',
            'moneda;',
            'metoda de plată;',
            'identificatorul tranzacției;',
            'statutul plății;',
            'factura emisă.',
          ] },
          { type: 'p', text: 'Toate plățile sunt procesate prin procesatori autorizați.' },
        ],
      },
      {
        heading: '7. Modalitățile prin care colectăm datele cu caracter personal',
        blocks: [
          { type: 'p', text: 'ISAD.academy colectează date cu caracter personal direct de la persoanele vizate sau indirect, prin intermediul sistemelor și serviciilor utilizate pentru furnizarea serviciilor educaționale și profesionale.' },
          { type: 'p', text: 'Datele pot fi colectate prin:' },
          { type: 'ul', items: [
            'accesarea website-ului;',
            'crearea unui cont de utilizator;',
            'completarea formularelor de înscriere;',
            'achiziționarea cursurilor sau serviciilor;',
            'participarea la cursuri online sau fizice;',
            'participarea la conferințe, workshopuri și webinarii;',
            'comunicarea prin e-mail;',
            'comunicarea telefonică;',
            'comunicarea prin WhatsApp, Microsoft Teams, Zoom sau alte platforme utilizate pentru desfășurarea activităților;',
            'participarea în comunitățile ISAD.academy;',
            'transmiterea documentelor necesare certificării;',
            'completarea chestionarelor de feedback;',
            'utilizarea platformei LMS;',
            'interacțiunea cu paginile oficiale de social media;',
            'utilizarea modulelor cookie și a tehnologiilor similare.',
          ] },
          { type: 'p', text: 'Datele pot fi colectate atât înaintea începerii relației contractuale, cât și pe întreaga durată a acesteia și ulterior, în limitele prevăzute de lege.' },
        ],
      },
      {
        heading: '8. Date colectate prin intermediul website-ului',
        blocks: [
          { type: 'p', text: 'La accesarea website-ului ISAD.academy pot fi colectate automat anumite informații tehnice necesare funcționării și securității Platformei.' },
          { type: 'p', text: 'Aceste informații pot include:' },
          { type: 'ul', items: [
            'adresa IP;',
            'tipul și versiunea browserului;',
            'sistemul de operare utilizat;',
            'tipul dispozitivului;',
            'rezoluția ecranului;',
            'limba browserului;',
            'fusul orar;',
            'data și ora accesării;',
            'paginile vizitate;',
            'durata sesiunii;',
            'sursa accesării (referrer);',
            'identificatori ai sesiunii;',
            'informații privind performanța website-ului;',
            'erori tehnice generate în timpul utilizării.',
          ] },
          { type: 'p', text: 'Aceste informații sunt utilizate pentru:' },
          { type: 'ul', items: [
            'administrarea website-ului;',
            'îmbunătățirea performanței Platformei;',
            'identificarea incidentelor de securitate;',
            'prevenirea fraudelor;',
            'analiză statistică;',
            'optimizarea experienței utilizatorilor.',
          ] },
          { type: 'p', text: 'În măsura în care aceste informații permit identificarea unei persoane fizice, ele sunt considerate date cu caracter personal și sunt prelucrate conform prezentei Politici.' },
        ],
      },
      {
        heading: '9. Date colectate prin intermediul Platformei LMS',
        blocks: [
          { type: 'p', text: 'Platforma LMS utilizată de ISAD.academy poate înregistra automat activitatea utilizatorilor în scopul furnizării serviciilor educaționale.' },
          { type: 'p', text: 'Pot fi colectate, fără a se limita la:' },
          { type: 'ul', items: [
            'data autentificării;',
            'ora autentificării;',
            'durata sesiunii;',
            'istoricul accesării cursurilor;',
            'modulele parcurse;',
            'procentul de progres;',
            'materialele descărcate;',
            'videoclipurile vizualizate;',
            'rezultatele testelor;',
            'timpul petrecut în fiecare lecție;',
            'proiectele încărcate;',
            'răspunsurile la evaluări;',
            'certificatele generate;',
            'istoricul certificărilor;',
            'badge-urile digitale acordate;',
            'activitatea din cadrul comunității Platformei.',
          ] },
          { type: 'p', text: 'Aceste informații permit:' },
          { type: 'ul', items: [
            'monitorizarea progresului educațional;',
            'emiterea certificatelor;',
            'reluarea cursurilor din punctul în care au fost întrerupte;',
            'acordarea accesului la resurse suplimentare;',
            'acordarea beneficiilor aferente abonamentelor.',
          ] },
        ],
      },
      {
        heading: '10. Date colectate în cadrul cursurilor, workshopurilor și conferințelor',
        blocks: [
          { type: 'p', text: 'În funcție de natura evenimentului, ISAD.academy poate colecta următoarele categorii de date:' },
          { type: 'ul', items: [
            'prezența la eveniment;',
            'semnătura pe lista de participare;',
            'fotografii realizate în cadrul evenimentului;',
            'înregistrări video;',
            'înregistrări audio;',
            'întrebări adresate lectorilor;',
            'rezultatele evaluărilor;',
            'feedback-ul oferit;',
            'informații privind participarea activă.',
          ] },
          { type: 'p', text: 'Aceste date sunt utilizate pentru:' },
          { type: 'ul', items: [
            'organizarea evenimentului;',
            'emiterea certificatelor;',
            'demonstrarea participării;',
            'îmbunătățirea serviciilor;',
            'promovarea activităților ISAD.academy, dacă există temei legal pentru aceasta.',
          ] },
        ],
      },
      {
        heading: '11. Date privind plățile și facturarea',
        blocks: [
          { type: 'p', text: 'În vederea furnizării serviciilor contractate, ISAD.academy prelucrează informații privind plățile efectuate.' },
          { type: 'p', text: 'Aceste informații pot include:' },
          { type: 'ul', items: [
            'numele plătitorului;',
            'adresa de facturare;',
            'codul fiscal (în cazul persoanelor juridice);',
            'denumirea companiei;',
            'istoricul comenzilor;',
            'valoarea achitată;',
            'TVA aplicabilă;',
            'moneda tranzacției;',
            'metoda de plată;',
            'identificatorul tranzacției;',
            'statutul plății;',
            'istoricul rambursărilor.',
          ] },
          { type: 'p', text: 'ISAD.academy nu stochează și nu are acces la datele complete ale cardurilor bancare utilizate pentru efectuarea plăților.' },
          { type: 'p', text: 'Procesarea plăților este realizată prin intermediul unor procesatori autorizați, care acționează ca operatori independenți sau persoane împuternicite, în funcție de relația contractuală existentă.' },
          { type: 'p', text: 'În scopul prevenirii fraudelor, ISAD.academy poate verifica anumite informații privind tranzacțiile și poate suspenda temporar furnizarea serviciilor în cazul existenței unor indicii rezonabile privind utilizarea frauduloasă a unui instrument de plată.' },
        ],
      },
      {
        heading: '12. Date privind evaluările și certificările',
        blocks: [
          { type: 'p', text: 'Pentru cursurile care presupun evaluare și emiterea unui certificat, ISAD.academy poate prelucra următoarele informații:' },
          { type: 'ul', items: [
            'rezultatele examenelor;',
            'notele obținute;',
            'răspunsurile la teste;',
            'proiectele realizate;',
            'evaluările efectuate de lectori;',
            'data promovării;',
            'seria certificatului;',
            'numărul certificatului;',
            'data emiterii;',
            'istoricul certificatelor.',
          ] },
          { type: 'p', text: 'Aceste date sunt utilizate exclusiv pentru:' },
          { type: 'ul', items: [
            'evaluarea competențelor;',
            'emiterea certificatelor;',
            'verificarea autenticității certificatelor;',
            'prevenirea falsificării documentelor;',
            'îndeplinirea obligațiilor legale sau contractuale.',
          ] },
        ],
      },
      {
        heading: '13. Înregistrări audio, video și fotografii',
        blocks: [
          { type: 'p', text: 'În cadrul anumitor cursuri, workshopuri, conferințe sau evenimente organizate de ISAD.academy pot fi realizate fotografii, înregistrări audio sau video.' },
          { type: 'p', text: 'Aceste înregistrări pot avea următoarele scopuri:' },
          { type: 'ul', items: [
            'desfășurarea activităților educaționale;',
            'permiterea accesului ulterior participanților;',
            'realizarea materialelor de suport;',
            'documentarea evenimentelor;',
            'promovarea activităților ISAD.academy;',
            'îmbunătățirea calității serviciilor.',
          ] },
          { type: 'p', text: 'Atunci când utilizarea imaginilor în scopuri promoționale necesită consimțământul persoanei vizate, acesta va fi solicitat separat, conform cerințelor legislației aplicabile.' },
          { type: 'p', text: 'Participanții sunt informați anterior începerii evenimentului cu privire la existența unor eventuale înregistrări audio-video.' },
        ],
      },
      {
        heading: '14. Scopurile prelucrării datelor cu caracter personal',
        blocks: [
          { type: 'p', text: 'ISAD.academy prelucrează datele cu caracter personal exclusiv în scopuri determinate, explicite și legitime, în conformitate cu dispozițiile Regulamentului (UE) 2016/679 (GDPR) și ale legislației naționale aplicabile.' },
          { type: 'p', text: 'Datele cu caracter personal pot fi prelucrate, după caz, pentru următoarele scopuri:' },
          { type: 'p', text: 'a) crearea și administrarea contului de utilizator;' },
          { type: 'p', text: 'b) furnizarea accesului la Platformă și la serviciile educaționale;' },
          { type: 'p', text: 'c) înscrierea la cursuri, webinarii, workshopuri, conferințe și alte evenimente;' },
          { type: 'p', text: 'd) administrarea abonamentelor și a pachetelor de servicii;' },
          { type: 'p', text: 'e) emiterea certificatelor de participare sau absolvire;' },
          { type: 'p', text: 'f) evaluarea progresului educațional și administrarea examenelor;' },
          { type: 'p', text: 'g) comunicarea cu utilizatorii privind serviciile contractate;' },
          { type: 'p', text: 'h) procesarea comenzilor și emiterea documentelor fiscale;' },
          { type: 'p', text: 'i) gestionarea solicitărilor, reclamațiilor și sesizărilor;' },
          { type: 'p', text: 'j) furnizarea suportului tehnic;' },
          { type: 'p', text: 'k) administrarea comunităților ISAD.academy;' },
          { type: 'p', text: 'l) organizarea sesiunilor de mentorat;' },
          { type: 'p', text: 'm) prevenirea fraudei și protejarea Platformei împotriva accesului neautorizat;' },
          { type: 'p', text: 'n) asigurarea securității informațiilor;' },
          { type: 'p', text: 'o) respectarea obligațiilor legale;' },
          { type: 'p', text: 'p) îmbunătățirea serviciilor furnizate;' },
          { type: 'p', text: 'q) realizarea analizelor statistice și operaționale;' },
          { type: 'p', text: 'r) desfășurarea campaniilor de marketing, în condițiile legii;' },
          { type: 'p', text: 's) exercitarea sau apărarea drepturilor în instanță;' },
          { type: 'p', text: 't) orice alte scopuri compatibile cu cele de mai sus, permise de legislația aplicabilă.' },
        ],
      },
      {
        heading: '15. Temeiurile legale ale prelucrării',
        blocks: [
          { type: 'p', text: 'ISAD.academy prelucrează datele cu caracter personal numai în măsura în care există un temei juridic prevăzut de articolul 6 din GDPR.' },
          { type: 'p', text: 'În funcție de situație, prelucrarea se poate baza pe unul sau mai multe dintre următoarele temeiuri:' },
          { type: 'p', text: '15.1 Executarea contractului' },
          { type: 'p', text: 'Datele sunt prelucrate atunci când acest lucru este necesar pentru:' },
          { type: 'ul', items: [
            'furnizarea accesului la Platformă;',
            'administrarea contului;',
            'livrarea cursurilor;',
            'organizarea evenimentelor;',
            'emiterea certificatelor;',
            'furnizarea mentoratului;',
            'acordarea accesului la resurse;',
            'procesarea plăților;',
            'emiterea facturilor.',
          ] },
          { type: 'p', text: '15.2 Respectarea obligațiilor legale' },
          { type: 'p', text: 'ISAD.academy poate prelucra date pentru respectarea obligațiilor impuse de legislația privind:' },
          { type: 'ul', items: [
            'contabilitatea;',
            'fiscalitatea;',
            'arhivarea documentelor;',
            'prevenirea fraudei;',
            'combaterea criminalității informatice;',
            'protecția consumatorilor;',
            'securitatea rețelelor informatice;',
            'alte obligații prevăzute de legislația aplicabilă.',
          ] },
          { type: 'p', text: '15.3 Interesul legitim' },
          { type: 'p', text: 'Operatorul poate prelucra date atunci când acest lucru este necesar pentru interesele sale legitime, fără a aduce atingere drepturilor și libertăților fundamentale ale persoanelor vizate.' },
          { type: 'p', text: 'Aceste interese pot include:' },
          { type: 'ul', items: [
            'dezvoltarea Platformei;',
            'îmbunătățirea experienței utilizatorilor;',
            'prevenirea utilizării frauduloase a conturilor;',
            'securitatea sistemelor informatice;',
            'audit intern;',
            'monitorizarea funcționării Platformei;',
            'apărarea drepturilor în instanță;',
            'prevenirea accesului neautorizat;',
            'detectarea tentativelor de fraudă;',
            'efectuarea analizelor statistice;',
            'măsurarea performanței serviciilor.',
          ] },
          { type: 'p', text: '15.4 Consimțământul' },
          { type: 'p', text: 'În situațiile în care legislația impune obținerea consimțământului, ISAD.academy va solicita acordul expres al persoanei vizate.' },
          { type: 'p', text: 'Acest lucru poate fi necesar, cu titlu exemplificativ, pentru:' },
          { type: 'ul', items: [
            'transmiterea newsletterelor;',
            'comunicări comerciale;',
            'utilizarea cookie-urilor neesențiale;',
            'publicarea fotografiilor în scop promoțional;',
            'utilizarea testimonialelor;',
            'participarea la campanii promoționale.',
          ] },
          { type: 'p', text: 'Consimțământul poate fi retras în orice moment, fără a afecta legalitatea prelucrării efectuate anterior retragerii acestuia.' },
        ],
      },
      {
        heading: '16. Comunicări comerciale și marketing',
        blocks: [
          { type: 'p', text: 'ISAD.academy poate transmite informații privind:' },
          { type: 'ul', items: [
            'lansarea unor cursuri noi;',
            'conferințe;',
            'webinarii;',
            'workshopuri;',
            'evenimente;',
            'reduceri;',
            'oferte speciale;',
            'programe educaționale;',
            'actualizări privind Platforma;',
            'articole și resurse educaționale.',
          ] },
          { type: 'p', text: 'Aceste comunicări vor fi transmise numai:' },
          { type: 'ul', items: [
            'în baza consimțământului persoanei vizate; sau',
            'în baza interesului legitim, în cazurile permise de lege.',
          ] },
          { type: 'p', text: 'Fiecare comunicare electronică de marketing va conține posibilitatea dezabonării rapide și gratuite.' },
          { type: 'p', text: 'Solicitarea de dezabonare produce efecte fără întârzieri nejustificate.' },
        ],
      },
      {
        heading: '17. Utilizarea instrumentelor bazate pe Inteligență Artificială',
        blocks: [
          { type: 'p', text: 'Pentru îmbunătățirea experienței educaționale și eficientizarea serviciilor, ISAD.academy poate utiliza instrumente bazate pe inteligență artificială („AI”).' },
          { type: 'p', text: 'Aceste instrumente pot fi utilizate pentru:' },
          { type: 'ul', items: [
            'generarea de conținut educațional;',
            'asistență în procesul de învățare;',
            'răspunsuri automate la întrebările utilizatorilor;',
            'traducerea materialelor;',
            'generarea de exemple și exerciții;',
            'organizarea informațiilor;',
            'automatizarea proceselor administrative.',
          ] },
          { type: 'p', text: 'ISAD.academy nu utilizează sistemele AI pentru adoptarea unor decizii exclusiv automate care produc efecte juridice asupra persoanelor vizate, cu excepția cazurilor permise de legislația aplicabilă.' },
          { type: 'p', text: 'Utilizarea instrumentelor AI nu elimină intervenția umană în procesele relevante și nu înlocuiește responsabilitatea Operatorului privind respectarea drepturilor persoanelor vizate.' },
        ],
      },
      {
        heading: '18. Cookie-uri și tehnologii similare',
        blocks: [
          { type: 'p', text: 'Website-ul ISAD.academy utilizează module cookie și tehnologii similare pentru:' },
          { type: 'ul', items: [
            'funcționarea Platformei;',
            'autentificarea utilizatorilor;',
            'memorarea preferințelor;',
            'analiza traficului;',
            'măsurarea performanței;',
            'personalizarea conținutului;',
            'securitatea serviciilor.',
          ] },
          { type: 'p', text: 'Cookie-urile sunt clasificate, după caz, în:' },
          { type: 'ul', items: [
            'cookie-uri strict necesare;',
            'cookie-uri funcționale;',
            'cookie-uri de analiză;',
            'cookie-uri de performanță;',
            'cookie-uri de marketing.',
          ] },
          { type: 'p', text: 'Detalii complete privind utilizarea cookie-urilor sunt prezentate în Politica privind modulele Cookie, document distinct.' },
        ],
      },
      {
        heading: '19. Profilare și procese automate',
        blocks: [
          { type: 'p', text: 'ISAD.academy poate utiliza procese automate limitate pentru:' },
          { type: 'ul', items: [
            'recomandarea cursurilor relevante;',
            'personalizarea conținutului educațional;',
            'afișarea progresului;',
            'acordarea badge-urilor;',
            'organizarea resurselor disponibile.',
          ] },
          { type: 'p', text: 'Aceste activități nu produc efecte juridice și nu determină decizii automate privind drepturile utilizatorilor.' },
          { type: 'p', text: 'În cazul în care, în viitor, vor fi implementate procese automate care intră sub incidența articolului 22 din GDPR, utilizatorii vor fi informați în mod corespunzător și vor beneficia de toate drepturile prevăzute de legislația aplicabilă.' },
        ],
      },
      {
        heading: '20. Perioada de păstrare a datelor cu caracter personal',
        blocks: [
          { type: 'p', text: 'ISAD.academy păstrează datele cu caracter personal numai pe perioada necesară îndeplinirii scopurilor pentru care acestea au fost colectate, precum și pentru respectarea obligațiilor legale aplicabile.' },
          { type: 'p', text: 'Perioada de păstrare poate varia în funcție de categoria datelor și de temeiul juridic al prelucrării.' },
          { type: 'p', text: 'Cu titlu orientativ:' },
          { type: 'p', text: 'Categoria datelor' },
          { type: 'p', text: 'Perioada de păstrare' },
          { type: 'p', text: 'Date aferente contului de utilizator' },
          { type: 'p', text: 'pe durata existenței contului și până la 3 ani după închiderea acestuia' },
          { type: 'p', text: 'Date privind comenzile și facturile' },
          { type: 'p', text: 'conform legislației fiscale și contabile aplicabile' },
          { type: 'p', text: 'Date privind certificatele emise' },
          { type: 'p', text: 'pe perioada necesară verificării autenticității acestora și arhivării' },
          { type: 'p', text: 'Date privind participarea la cursuri' },
          { type: 'p', text: 'pe perioada relației contractuale și ulterior, în scopul evidenței istoricului educațional' },
          { type: 'p', text: 'Solicitări și reclamații' },
          { type: 'p', text: 'până la soluționarea definitivă și ulterior conform termenelor legale' },
          { type: 'p', text: 'Date utilizate în scop de marketing' },
          { type: 'p', text: 'până la retragerea consimțământului sau exercitarea dreptului de opoziție' },
          { type: 'p', text: 'Loguri tehnice și de securitate' },
          { type: 'p', text: 'atât timp cât este necesar pentru securitatea Platformei și investigarea incidentelor' },
          { type: 'p', text: 'La expirarea perioadelor de păstrare, datele vor fi șterse, anonimizate sau arhivate, după caz, în conformitate cu obligațiile legale.' },
        ],
      },
      {
        heading: '21. Securitatea datelor',
        blocks: [
          { type: 'p', text: 'ISAD.academy implementează măsuri tehnice și organizatorice adecvate pentru protejarea datelor cu caracter personal împotriva:' },
          { type: 'ul', items: [
            'accesului neautorizat;',
            'divulgării accidentale sau ilegale;',
            'modificării neautorizate;',
            'distrugerii;',
            'pierderii;',
            'utilizării abuzive.',
          ] },
          { type: 'p', text: 'Aceste măsuri pot include, fără a se limita la:' },
          { type: 'ul', items: [
            'criptarea comunicațiilor prin protocoale securizate (SSL/TLS);',
            'autentificarea utilizatorilor;',
            'controlul accesului pe bază de roluri;',
            'parole securizate și stocate în format criptat;',
            'copii de siguranță (backup);',
            'monitorizarea infrastructurii;',
            'actualizarea periodică a sistemelor informatice;',
            'protecție antivirus și anti-malware;',
            'firewall-uri și mecanisme de detecție a accesului neautorizat;',
            'audituri periodice de securitate.',
          ] },
          { type: 'p', text: 'Deși depunem toate eforturile rezonabile pentru protejarea datelor, niciun sistem informatic nu poate garanta securitatea absolută.' },
        ],
      },
      {
        heading: '22. Destinatarii datelor cu caracter personal',
        blocks: [
          { type: 'p', text: 'În funcție de natura serviciilor furnizate, ISAD.academy poate transmite date cu caracter personal următoarelor categorii de destinatari:' },
          { type: 'ul', items: [
            'furnizori ai platformei LMS;',
            'furnizori de servicii cloud;',
            'procesatori de plăți;',
            'furnizori de servicii de găzduire (hosting);',
            'furnizori de servicii IT;',
            'furnizori de servicii de e-mail;',
            'furnizori de servicii CRM;',
            'furnizori de servicii de videoconferință;',
            'furnizori de servicii de analiză și monitorizare;',
            'consultanți juridici;',
            'consultanți fiscali și contabili;',
            'auditori;',
            'instituții publice și autorități competente, atunci când există o obligație legală.',
          ] },
          { type: 'p', text: 'Toți furnizorii care prelucrează date în numele ISAD.academy sunt selectați cu atenție și sunt obligați contractual să respecte cerințele GDPR și standarde adecvate de securitate.' },
          { type: 'p', text: 'ISAD.academy nu vinde și nu închiriază datele cu caracter personal către terți.' },
        ],
      },
      {
        heading: '23. Transferuri internaționale de date',
        blocks: [
          { type: 'p', text: 'În anumite situații, furnizorii utilizați de ISAD.academy pot stoca sau prelucra date în afara Spațiului Economic European (SEE).' },
          { type: 'p', text: 'În astfel de cazuri, transferurile se vor realiza numai dacă sunt respectate condițiile prevăzute de articolele 44–49 din GDPR, inclusiv prin:' },
          { type: 'ul', items: [
            'decizii de adecvare emise de Comisia Europeană;',
            'Clauze Contractuale Standard (Standard Contractual Clauses – SCC);',
            'alte garanții adecvate prevăzute de legislația aplicabilă.',
          ] },
          { type: 'p', text: 'ISAD.academy depune toate eforturile pentru a utiliza furnizori care oferă un nivel adecvat de protecție a datelor cu caracter personal.' },
        ],
      },
      {
        heading: '24. Drepturile persoanelor vizate',
        blocks: [
          { type: 'p', text: 'În conformitate cu GDPR, persoanele vizate beneficiază de următoarele drepturi:' },
          { type: 'ul', items: [
            'dreptul de acces;',
            'dreptul la rectificare;',
            'dreptul la ștergere („dreptul de a fi uitat”);',
            'dreptul la restricționarea prelucrării;',
            'dreptul la portabilitatea datelor;',
            'dreptul la opoziție;',
            'dreptul de a nu face obiectul unei decizii bazate exclusiv pe prelucrare automată, inclusiv profilare;',
            'dreptul de retragere a consimțământului;',
            'dreptul de a depune o plângere la autoritatea competentă.',
          ] },
          { type: 'p', text: 'Exercitarea acestor drepturi este gratuită, cu excepția cazurilor în care solicitările sunt în mod vădit nefondate sau excesive, conform prevederilor legale.' },
        ],
      },
      {
        heading: '25. Exercitarea drepturilor',
        blocks: [
          { type: 'p', text: 'Solicitările privind exercitarea drepturilor prevăzute de prezenta Politică pot fi transmise la:' },
          { type: 'p', text: 'E-mail: support@isad.academy' },
          { type: 'p', text: 'ISAD.academy va răspunde solicitărilor fără întârzieri nejustificate și, în orice caz, în termenul prevăzut de legislația aplicabilă.' },
          { type: 'p', text: 'În situațiile în care există îndoieli rezonabile cu privire la identitatea solicitantului, Operatorul poate solicita informații suplimentare necesare verificării identității.' },
        ],
      },
      {
        heading: '26. Autoritatea de supraveghere',
        blocks: [
          { type: 'p', text: 'În cazul în care considerați că drepturile dumneavoastră privind protecția datelor au fost încălcate, aveți dreptul de a depune o plângere la:' },
          { type: 'p', text: 'Autoritatea Națională de Supraveghere a Prelucrării Datelor cu Caracter Personal (ANSPDCP)' },
          { type: 'p', text: 'De asemenea, aveți dreptul de a vă adresa instanțelor competente, în condițiile legii.' },
        ],
      },
      {
        heading: '27. Actualizarea Politicii de Confidențialitate',
        blocks: [
          { type: 'p', text: 'ISAD.academy își rezervă dreptul de a modifica prezenta Politică ori de câte ori este necesar, inclusiv ca urmare a:' },
          { type: 'ul', items: [
            'modificărilor legislative;',
            'modificărilor serviciilor oferite;',
            'introducerii unor funcționalități noi;',
            'modificării furnizorilor sau tehnologiilor utilizate;',
            'implementării unor noi cerințe privind securitatea informațiilor.',
          ] },
          { type: 'p', text: 'Versiunea actualizată va fi publicată pe website, iar data ultimei actualizări va fi indicată în partea introductivă a documentului.' },
          { type: 'p', text: 'Utilizarea în continuare a Platformei după publicarea modificărilor constituie acceptarea acestora, în măsura permisă de legislația aplicabilă.' },
        ],
      },
      {
        heading: '28. Date de contact',
        blocks: [
          { type: 'p', text: 'Pentru orice întrebări privind prezenta Politică de Confidențialitate sau modul în care ISAD.academy prelucrează datele cu caracter personal, ne puteți contacta la:' },
          { type: 'p', text: 'INTERNATIONAL SECURITY AND DEFENCE S.R.L.' },
          { type: 'p', text: 'Website: https://isad.academy' },
          { type: 'p', text: 'E-mail: support@isad.academy' },
        ],
      },
    ],
  },
}

export default privacy
