/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    courseSessions: CourseSession;
    orders: Order;
    discountCodes: DiscountCode;
    reviews: Review;
    blogPosts: BlogPost;
    faqItems: FaqItem;
    leads: Lead;
    legalPages: LegalPage;
    newsletters: Newsletter;
    eventPopups: EventPopup;
    eventRegistrations: EventRegistration;
    eventEmails: EventEmail;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    courses: {
      sessions: 'courseSessions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    courseSessions: CourseSessionsSelect<false> | CourseSessionsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    discountCodes: DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    blogPosts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    faqItems: FaqItemsSelect<false> | FaqItemsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    legalPages: LegalPagesSelect<false> | LegalPagesSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    eventPopups: EventPopupsSelect<false> | EventPopupsSelect<true>;
    eventRegistrations: EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    eventEmails: EventEmailsSelect<false> | EventEmailsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ro') | ('en' | 'ro')[];
  globals: {
    siteSettings: SiteSetting;
    homepage: Homepage;
    expertBio: ExpertBio;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    expertBio: ExpertBioSelect<false> | ExpertBioSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'ro';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendReviewRequests: TaskSendReviewRequests;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Payload admin users only. Clients never log in.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Course teasers shown in the catalog. Editions (dates/prices/seats) live on Course Sessions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Auto-generated from "title" on first save. Edit to override — must stay unique.
   */
  slug?: string | null;
  /**
   * Short blurb shown on the course preview cards (Home "Explore our upcoming courses"). Keep it to 1–2 sentences.
   */
  shortDescription?: string | null;
  /**
   * Banner image shown on the catalog card and course detail header.
   */
  image?: (number | null) | Media;
  /**
   * Total course length in hours.
   */
  durationHours?: number | null;
  /**
   * Reserved for future catalog filtering — no filter UI at launch (CLAUDE.md §6).
   */
  category?: ('iso' | 'antiFraud' | 'security' | 'other') | null;
  /**
   * Full course description. Placeholder copy until Silviu confirms real content (CLAUDE.md §15).
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * "Who this course is for" — one row per bullet point.
   */
  audience?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * CPD credits are 1 per course hour (house rule C3, CLAUDE.md §9 R2) and derive automatically from Duration (hours). This field is only used as a fallback for courses whose Duration is left empty.
   */
  certificationCredits?: number | null;
  /**
   * Editions of this course. Add/edit them from the Course Sessions collection.
   */
  sessions?: {
    docs?: (number | CourseSession)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Quiz matching tags. Fill these in so the course quiz can recommend this course. Leave Level empty to keep the course OUT of the quiz.
   */
  quizProfile?: {
    /**
     * Depth of the course. Required for the course to appear in quiz results.
     */
    level?: ('introductory' | 'intermediate' | 'advanced' | 'specialization') | null;
    /**
     * What a participant walks away with (pick all that apply).
     */
    outcomes?:
      | ('overview' | 'practicalSkills' | 'implementationPlan' | 'auditPrep' | 'certification' | 'foundationForMore')[]
      | null;
    /**
     * Mirrors quiz question 2 ("Ce domeniu te interesează cel mai mult?") — pick all that apply.
     */
    domains?:
      | (
          'isoManagement' | 'quality' | 'sustainability' | 'riskCompliance' | 'infosec' | 'ai' | 'leadership' | 'audit'
        )[]
      | null;
    /**
     * One–two sentences shown on the quiz result screen ("why we recommend it"). The quiz is in Romanian — write the RO version at least.
     */
    quizPitch?: string | null;
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Editions of a course — dates, schedule, capacity and price windows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseSessions".
 */
export interface CourseSession {
  id: number;
  course: number | Course;
  startDate: string;
  /**
   * Concrete days and hours this edition meets.
   */
  schedule?:
    | {
        date: string;
        /**
         * e.g. "09:00"
         */
        startTime: string;
        /**
         * e.g. "17:00"
         */
        endTime: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Total seats for this edition.
   */
  capacity: number;
  /**
   * Consumed only on a CONFIRMED order, atomically (T5). Do not edit by hand.
   */
  seatsSold?: number | null;
  /**
   * Idempotency stamp for the daily review-request job (T13, CLAUDE.md §10) — set once the post-session review-request emails have been sent for this edition (best-effort: stamped even if some individual sends failed, so the job never re-mails everyone on a retry). Never set by hand.
   */
  reviewRequestSentAt?: string | null;
  /**
   * Early Bird price window. Leave empty if this edition has none.
   */
  earlyBird?: {
    price?: number | null;
    /**
     * Charged to visitors from Romania (B1 — geo-based currency). Leave empty to sell this window in EUR only.
     */
    priceRON?: number | null;
    startDate?: string | null;
    /**
     * Leave both dates empty if there is no early bird window.
     */
    endDate?: string | null;
  };
  /**
   * Standard price window.
   */
  standard?: {
    price?: number | null;
    /**
     * Charged to visitors from Romania (B1 — geo-based currency). Leave empty to sell this window in EUR only.
     */
    priceRON?: number | null;
    startDate?: string | null;
    /**
     * Leave both dates empty if there is no standard window.
     */
    endDate?: string | null;
  };
  /**
   * Computed: capacity − seatsSold. Not stored.
   */
  seatsRemaining?: number | null;
  /**
   * Computed from dates, seats and price windows. Not stored.
   */
  status?: ('upcoming' | 'past' | 'soldOut' | 'noActiveWindow') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Checkout orders. Server-side only — never exposed to the public API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  session: number | CourseSession;
  quantity: number;
  buyer: {
    name: string;
    email: string;
    phone?: string | null;
    isCompany?: boolean | null;
    companyName?: string | null;
    cui?: string | null;
    address?: string | null;
  };
  /**
   * One row per seat — length must equal "quantity". When quantity is 1, the checkout API fills this from the buyer.
   */
  participants?:
    | {
        name: string;
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Snapshot of the pricing engine output at the moment of purchase (CLAUDE.md §8) — never recomputed after the fact. Read-only: not hand-editable.
   */
  pricing?: {
    basePrice?: number | null;
    /**
     * Visitor currency resolved by geo at purchase time (B1).
     */
    currency?: ('EUR' | 'RON') | null;
    appliedWindow?: ('earlyBird' | 'standard') | null;
    groupDiscount?: number | null;
    memberDiscount?: number | null;
    code?: (number | null) | DiscountCode;
    codes?: (number | DiscountCode)[] | null;
    codeDiscount?: number | null;
    total?: number | null;
  };
  paymentStatus: 'pending' | 'confirmed' | 'failed' | 'refunded';
  /**
   * Payment provider that handled this order, e.g. "mock", "stripe". Set by checkout — read-only.
   */
  provider?: string | null;
  /**
   * Provider's transaction/session reference. Set by checkout — read-only.
   */
  providerRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Discount codes. Never publicly readable — checkout validates codes server-side.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discountCodes".
 */
export interface DiscountCode {
  id: number;
  code: string;
  percentage: number;
  expiresAt?: string | null;
  /**
   * Leave empty for unlimited uses.
   */
  usageLimit?: number | null;
  /**
   * Incremented by checkout when the code is applied. Do not edit by hand.
   */
  usageCount?: number | null;
  /**
   * "member" codes also grant the member discount (CLAUDE.md §8, §13 — % TBD).
   */
  type: 'general' | 'member';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Testimonials. No rating — curate homepage placement with "Show on home" (max 5 shown).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  text: string;
  authorName?: string | null;
  roleCompany?: string | null;
  photo?: (number | null) | Media;
  /**
   * Which course this review refers to, if any.
   */
  course?: (number | null) | Course;
  source: 'emailForm' | 'manual';
  /**
   * Silviu curates which testimonials appear on Home — max 5 are shown, enforced in the query.
   */
  showOnHome?: boolean | null;
  /**
   * T13 duplicate-submission guard — sha256(sessionId + ":" + lowercased email), set only by the public /api/reviews/submit route so the same (session, email) pair can submit at most once. Left empty for manually-added reviews (a nullable unique column allows any number of empty values in Postgres — effectively "sparse").
   */
  submissionKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles — rich text supports named colors, link chips and downloadable resources.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Auto-generated from "title" on first save. Edit to override — must stay unique.
   */
  slug?: string | null;
  /**
   * Optional — articles may be published without a cover image.
   */
  coverImage?: (number | null) | Media;
  excerpt?: string | null;
  /**
   * Supports colored text, blockquotes, in-text images, link chips (external pill links) and downloadable resources.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Defaults to Dr. Silviu Gresoi — editable per article.
   */
  author?: string | null;
  /**
   * Reserved for future filtering — no filter UI at launch (CLAUDE.md §6).
   */
  category?: ('aiGovernance' | 'antiFraud' | 'riskManagement' | 'other') | null;
  /**
   * Minutes. Leave empty to auto-estimate from the body (~200 words/min); a manual value always wins.
   */
  readingTime?: number | null;
  /**
   * If enabled, the article shows a gated email form that delivers the attached file.
   */
  leadMagnet?: {
    /**
     * Gate the file behind an email capture form.
     */
    enabled?: boolean | null;
    /**
     * Delivered to visitors who submit their email. Required while "enabled" is checked.
     */
    file?: (number | null) | Media;
  };
  /**
   * Toggle "related to a course" — shows a course callout at the end of the article.
   */
  relatedCourse?: (number | null) | Course;
  /**
   * Uncheck to publish WITHOUT emailing subscribers. First publish only — the broadcast is ever sent once. Publishing unchecked keeps that one send available: unpublish, tick the box and publish again to send it later.
   */
  sendNewsletterOnPublish?: boolean | null;
  /**
   * Set automatically once the first-publish newsletter broadcast has been attempted (T7) — prevents re-sending on subsequent re-saves/re-publishes. Do not edit by hand.
   */
  broadcastSentAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Q&A shown in the FAQ section on the homepage, grouped by journey tab.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqItems".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tab the question appears under in the homepage FAQ section.
   */
  category?: ('discover' | 'learn' | 'validate' | 'access') | null;
  /**
   * Display order, ascending.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact + Corporate form submissions. Public create only — read/update/delete are admin-only.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'contact' | 'corporate';
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  /**
   * Contact form only.
   */
  subject?: ('course' | 'corporate' | 'certification' | 'other') | null;
  /**
   * Corporate form only.
   */
  companyName?: string | null;
  /**
   * Corporate form only.
   */
  contactPerson?: string | null;
  /**
   * Corporate form only — free-text range, e.g. "10-20".
   */
  participantsRange?: string | null;
  /**
   * Corporate form only — pick an existing catalog course as the requested topic.
   */
  topicCourse?: (number | null) | Course;
  /**
   * Corporate form only — free-text topic when it is not one of the catalog courses.
   */
  topicOther?: string | null;
  /**
   * Corporate form only — preferred delivery window.
   */
  preferredPeriod?: {
    from?: string | null;
    to?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The full text of the legal pages. What you save here is what visitors read — nothing is hard-coded any more.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages".
 */
export interface LegalPage {
  id: number;
  /**
   * Which route this document renders on. One document per page.
   */
  page: 'terms' | 'privacy' | 'cookies';
  /**
   * Browser tab / SEO title, e.g. "Terms and Conditions".
   */
  metaTitle: string;
  /**
   * First part of the on-page heading, in plain ink — e.g. "Terms and " (mind the trailing space).
   */
  titlePlain?: string | null;
  /**
   * Last part of the heading, rendered in the brand gradient — e.g. "Conditions."
   */
  titleGradient?: string | null;
  /**
   * Shown verbatim under the title, e.g. "Last updated: 21.07.2026". Free text on purpose — it is the date OF THE DOCUMENT, not of the last save, and those two must not be confused.
   */
  lastUpdated?: string | null;
  /**
   * Numbered sections. Put the number in the heading, e.g. "1. General information". Leave the heading empty for the preamble.
   */
  sections?:
    | {
        /**
         * Verbatim from the document. Empty = no heading (preamble).
         */
        heading?: string | null;
        blocks?:
          | (
              | {
                  text: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'paragraph';
                }
              | {
                  /**
                   * e.g. "3.1. Provider" or "Identification data".
                   */
                  text: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'subheading';
                }
              | {
                  items?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'list';
                }
              | {
                  headLeft: string;
                  headRight: string;
                  rows?:
                    | {
                        left: string;
                        right: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'table';
                }
              | {
                  /**
                   * e.g. the legal name and registration numbers.
                   */
                  line1: string;
                  /**
                   * e.g. contact e-mails, phone, website.
                   */
                  line2: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'entity';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Write a newsletter and send it to everyone subscribed. Tick “Send now” and save — the message goes out once and cannot be re-sent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  /**
   * Subject line recipients see in their inbox.
   */
  subject: string;
  /**
   * Optional one-line intro shown under the title. Leave empty to skip it.
   */
  preheader?: string | null;
  /**
   * The message. Headings, bold, italic, links and lists are carried into the e-mail; images and embeds are not.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Tick and save to send. Sending happens once — this cannot be undone.
   */
  sendNow?: boolean | null;
  /**
   * Stamped when the newsletter was sent. Once set, it can never be re-sent.
   */
  sentAt?: string | null;
  /**
   * Outcome of the send — check here if the newsletter did not arrive.
   */
  lastResult?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One entry per live event. A pop-up shows on the site only while it is "Published" AND the clock is between "Start showing at" and the event date — after the event it disappears on its own. "Registrations" counts the people who signed up for THAT event; their details are in Event Registrations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventPopups".
 */
export interface EventPopup {
  id: number;
  /**
   * Only visible here, to tell events apart. Not shown to visitors.
   */
  internalName: string;
  /**
   * Auto-generated from "internalName" on first save. Edit to override — must stay unique.
   */
  slug?: string | null;
  /**
   * Only "Published" is ever shown on the site.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Bumped by "Force re-show". Visitors who dismissed an older version see it again.
   */
  displayVersion?: number | null;
  /**
   * Tick and save to show this pop-up again to people who dismissed it. Those who already registered never see it again.
   */
  forceReshow?: boolean | null;
  /**
   * Event title — the part rendered in plain ink, e.g. "AI Governance ".
   */
  titlePlain?: string | null;
  /**
   * Event title — the segment rendered in the brand gradient, e.g. "in Practice.".
   */
  titleGradient?: string | null;
  description?: string | null;
  /**
   * E.g. "Thu 14 Aug 2026 · 18:00 (EEST) · Live on Zoom".
   */
  metaLine?: string | null;
  /**
   * Shown with photo, or initials when no photo is uploaded.
   */
  speakers?:
    | {
        name: string;
        role?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Main button label. Empty = "Secure your spot".
   */
  ctaLabel?: string | null;
  /**
   * Form submit label. Empty = "Join us".
   */
  joinLabel?: string | null;
  /**
   * Options offered in the registration form (visitors can also type their own).
   */
  occupations?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Countdown target. The pop-up disappears on its own after this moment — no need to unpublish it.
   */
  eventDate: string;
  /**
   * From when the pop-up may appear. Must be before the event date.
   */
  startShowingAt: string;
  /**
   * Seconds on the page before the pop-up appears.
   */
  showDelaySeconds?: number | null;
  /**
   * Show the (unticked) newsletter opt-in in the registration form.
   */
  newsletterOptInEnabled?: boolean | null;
  /**
   * Wording shown next to the opt-in. Stored as a snapshot on every registration — GDPR proof of what exactly was agreed to.
   */
  newsletterConsentText?: string | null;
  /**
   * How many people signed up for this event.
   */
  registrationsCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everyone who signed up through an event pop-up. Each row belongs to ONE event — see the "Popup" column. Use Filters → Popup to see a single event’s list. Signing up for one event never signs anyone up for another, and it does not subscribe them to the newsletter unless they ticked that box.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations".
 */
export interface EventRegistration {
  id: number;
  /**
   * Which event pop-up this sign-up came from.
   */
  popup: number | EventPopup;
  firstName: string;
  lastName: string;
  email: string;
  /**
   * Picked from the configured list or typed freely.
   */
  occupation?: string | null;
  /**
   * Ticked the newsletter box when registering. This alone does NOT make them a subscriber — they still have to confirm the double opt-in e-mail.
   */
  newsletterOptIn?: boolean | null;
  /**
   * GDPR proof: the exact wording agreed to, and when. Kept as a snapshot because the pop-up’s consent text can be edited later — the proof must not change with it.
   */
  consentSnapshot?: {
    consentText?: string | null;
    consentedAt?: string | null;
    ip?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Write an e-mail and send it to everyone registered for ONE event. Tick "Send test to me" first to see how it looks; then "Send now" delivers it to the whole list — once, and it cannot be re-sent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventEmails".
 */
export interface EventEmail {
  id: number;
  /**
   * Which event’s registrants receive this. Nobody else gets it.
   */
  popup: number | EventPopup;
  /**
   * Subject line. Variables work here too, e.g. {{firstName}}.
   */
  subject: string;
  /**
   * Variables: {{firstName}}, {{lastName}}, {{eventTitle}}, {{eventDate}}, {{joinUrl}} — replaced per recipient. Headings, bold, links and lists carry into the e-mail; images and embeds do not.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Zoom/Meet link, filled in per e-mail rather than on the event (owner 2026-08-07): the link often does not exist yet when the pop-up is created, and a reminder may point somewhere different from the invitation. Becomes the {{joinUrl}} variable. Leave empty if the e-mail does not need it.
   */
  joinUrl?: string | null;
  /**
   * Sends ONE copy to your own account e-mail, with sample names filled into the variables. Changes nothing else — use it as the preview.
   */
  sendTestNow?: boolean | null;
  /**
   * Tick and save to send to every registrant of the selected event. Works ONCE — re-saving afterwards sends nothing. If some addresses failed, ticking it again retries only those.
   */
  sendNow?: boolean | null;
  status?: ('draft' | 'sent' | 'failed') | null;
  /**
   * What happened on the last attempt — read this after ticking a box.
   */
  lastResult?: string | null;
  sentAt?: string | null;
  /**
   * Which admin pressed send — an audit trail, NOT the sender address. E-mails always go out from the newsletter sender (news@isad.academy).
   */
  sentBy?: (number | null) | User;
  recipientCount?: number | null;
  successCount?: number | null;
  /**
   * Addresses the provider refused, with the reason. Retry targets exactly these.
   */
  failures?:
    | {
        email?: string | null;
        error?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendReviewRequests';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendReviewRequests') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'courseSessions';
        value: number | CourseSession;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'discountCodes';
        value: number | DiscountCode;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'blogPosts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'faqItems';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'legalPages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'eventPopups';
        value: number | EventPopup;
      } | null)
    | ({
        relationTo: 'eventRegistrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'eventEmails';
        value: number | EventEmail;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  image?: T;
  durationHours?: T;
  category?: T;
  description?: T;
  audience?:
    | T
    | {
        text?: T;
        id?: T;
      };
  certificationCredits?: T;
  sessions?: T;
  quizProfile?:
    | T
    | {
        level?: T;
        outcomes?: T;
        domains?: T;
        quizPitch?: T;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseSessions_select".
 */
export interface CourseSessionsSelect<T extends boolean = true> {
  course?: T;
  startDate?: T;
  schedule?:
    | T
    | {
        date?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  capacity?: T;
  seatsSold?: T;
  reviewRequestSentAt?: T;
  earlyBird?:
    | T
    | {
        price?: T;
        priceRON?: T;
        startDate?: T;
        endDate?: T;
      };
  standard?:
    | T
    | {
        price?: T;
        priceRON?: T;
        startDate?: T;
        endDate?: T;
      };
  seatsRemaining?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  session?: T;
  quantity?: T;
  buyer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        isCompany?: T;
        companyName?: T;
        cui?: T;
        address?: T;
      };
  participants?:
    | T
    | {
        name?: T;
        email?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        basePrice?: T;
        currency?: T;
        appliedWindow?: T;
        groupDiscount?: T;
        memberDiscount?: T;
        code?: T;
        codes?: T;
        codeDiscount?: T;
        total?: T;
      };
  paymentStatus?: T;
  provider?: T;
  providerRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discountCodes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  percentage?: T;
  expiresAt?: T;
  usageLimit?: T;
  usageCount?: T;
  type?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  text?: T;
  authorName?: T;
  roleCompany?: T;
  photo?: T;
  course?: T;
  source?: T;
  showOnHome?: T;
  submissionKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  category?: T;
  readingTime?: T;
  leadMagnet?:
    | T
    | {
        enabled?: T;
        file?: T;
      };
  relatedCourse?: T;
  sendNewsletterOnPublish?: T;
  broadcastSentAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqItems_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  subject?: T;
  companyName?: T;
  contactPerson?: T;
  participantsRange?: T;
  topicCourse?: T;
  topicOther?: T;
  preferredPeriod?:
    | T
    | {
        from?: T;
        to?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  page?: T;
  metaTitle?: T;
  titlePlain?: T;
  titleGradient?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        heading?: T;
        blocks?:
          | T
          | {
              paragraph?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              subheading?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              list?:
                | T
                | {
                    items?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              table?:
                | T
                | {
                    headLeft?: T;
                    headRight?: T;
                    rows?:
                      | T
                      | {
                          left?: T;
                          right?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              entity?:
                | T
                | {
                    line1?: T;
                    line2?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  subject?: T;
  preheader?: T;
  body?: T;
  sendNow?: T;
  sentAt?: T;
  lastResult?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventPopups_select".
 */
export interface EventPopupsSelect<T extends boolean = true> {
  internalName?: T;
  slug?: T;
  status?: T;
  displayVersion?: T;
  forceReshow?: T;
  titlePlain?: T;
  titleGradient?: T;
  description?: T;
  metaLine?: T;
  speakers?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  ctaLabel?: T;
  joinLabel?: T;
  occupations?:
    | T
    | {
        label?: T;
        id?: T;
      };
  eventDate?: T;
  startShowingAt?: T;
  showDelaySeconds?: T;
  newsletterOptInEnabled?: T;
  newsletterConsentText?: T;
  registrationsCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  popup?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  occupation?: T;
  newsletterOptIn?: T;
  consentSnapshot?:
    | T
    | {
        consentText?: T;
        consentedAt?: T;
        ip?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventEmails_select".
 */
export interface EventEmailsSelect<T extends boolean = true> {
  popup?: T;
  subject?: T;
  body?: T;
  joinUrl?: T;
  sendTestNow?: T;
  sendNow?: T;
  status?: T;
  lastResult?: T;
  sentAt?: T;
  sentBy?: T;
  recipientCount?: T;
  successCount?: T;
  failures?:
    | T
    | {
        email?: T;
        error?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide configuration, including the business decisions still pending from Silviu (CLAUDE.md §13).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Show "X seats left" only when seatsRemaining is below this number.
   */
  seatsThreshold?: number | null;
  /**
   * TBD from Silviu (CLAUDE.md §13). Default: EUR.
   */
  currency?: ('EUR' | 'RON') | null;
  /**
   * TBD from Silviu (CLAUDE.md §13). Default: VAT included.
   */
  vatDisplay?: ('incl' | 'excl') | null;
  /**
   * TBD from Silviu (CLAUDE.md §13). Default: show both windows.
   */
  earlyBirdDisplay?: ('bothWindows' | 'activeOnly') | null;
  /**
   * CRITICAL — TBD from Silviu (CLAUDE.md §8, §13). All three strategies are implemented (T4); this only selects which one applies. Default: stackAll.
   */
  stackingPolicy?: ('stackAll' | 'bestOf' | 'groupMemberStack_codeExclusive') | null;
  /**
   * Member discount % — TBD by Silviu; 0 disables member pricing.
   */
  memberDiscountPercent?: number | null;
  /**
   * Legal entity details for the footer + invoices. TBD from Silviu — footer degrades gracefully while empty.
   */
  legalEntity?: {
    name?: string | null;
    cui?: string | null;
    address?: string | null;
    anpcUrl?: string | null;
    solUrl?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    linkedin?: string | null;
  };
  /**
   * Optional overrides for the env-based GA4/GTM IDs. Consent-gated + lazy-loaded (CLAUDE.md §7).
   */
  analytics?: {
    ga4Id?: string | null;
    gtmId?: string | null;
    gscVerification?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage content: hero, featured courses, trust stats and newsletter block.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
    visual?: (number | null) | Media;
  };
  /**
   * Courses shown in the "Featured courses" section — Silviu chooses.
   */
  featuredCourses?: (number | Course)[] | null;
  whyIsad?: {
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    differentiators?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    headline?: string | null;
    invitationText?: string | null;
    /**
     * Optional — offer a downloadable resource in exchange for a newsletter signup.
     */
    leadMagnet?: {
      /**
       * Gate the file behind an email capture form.
       */
      enabled?: boolean | null;
      /**
       * Delivered to visitors who submit their email. Required while "enabled" is checked.
       */
      file?: (number | null) | Media;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The expert bio, shown on Home (short) and About (full).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertBio".
 */
export interface ExpertBio {
  id: number;
  name?: string | null;
  /**
   * Professional title / headline.
   */
  title?: string | null;
  photo?: (number | null) | Media;
  /**
   * Used in the Home expert band.
   */
  shortBio?: string | null;
  /**
   * Used on the About page.
   */
  fullBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  credentials?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  seatsThreshold?: T;
  currency?: T;
  vatDisplay?: T;
  earlyBirdDisplay?: T;
  stackingPolicy?: T;
  memberDiscountPercent?: T;
  legalEntity?:
    | T
    | {
        name?: T;
        cui?: T;
        address?: T;
        anpcUrl?: T;
        solUrl?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        linkedin?: T;
      };
  analytics?:
    | T
    | {
        ga4Id?: T;
        gtmId?: T;
        gscVerification?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaText?: T;
        ctaLink?: T;
        visual?: T;
      };
  featuredCourses?: T;
  whyIsad?:
    | T
    | {
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        differentiators?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        headline?: T;
        invitationText?: T;
        leadMagnet?:
          | T
          | {
              enabled?: T;
              file?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertBio_select".
 */
export interface ExpertBioSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  shortBio?: T;
  fullBio?: T;
  credentials?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendReviewRequests".
 */
export interface TaskSendReviewRequests {
  input?: unknown;
  output: {
    sessionsProcessed?: number | null;
    emailsSent?: number | null;
    emailsFailed?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkChipBlock".
 */
export interface LinkChipBlock {
  /**
   * Button text, e.g. "Watch the interview".
   */
  label: string;
  /**
   * Absolute http(s) URL the chip links to.
   */
  url: string;
  /**
   * Shown next to the label so readers know where the link leads.
   */
  platform?: ('youtube' | 'linkedin' | 'website' | 'other') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'linkChip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadableResourceBlock".
 */
export interface DownloadableResourceBlock {
  title: string;
  /**
   * Optional one-liner shown under the title.
   */
  description?: string | null;
  file: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'downloadableResource';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}