/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    courses: Course;
    courseSessions: CourseSession;
    trainers: Trainer;
    orders: Order;
    discountCodes: DiscountCode;
    partners: Partner;
    reviews: Review;
    blogPosts: BlogPost;
    faqItems: FaqItem;
    leads: Lead;
    legalPages: LegalPage;
    newsletters: Newsletter;
    eventPopups: EventPopup;
    eventRegistrations: EventRegistration;
    eventEmails: EventEmail;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    courses: {
      sessions: 'courseSessions';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    courses: CoursesSelect<false> | CoursesSelect<true>;
    courseSessions: CourseSessionsSelect<false> | CourseSessionsSelect<true>;
    trainers: TrainersSelect<false> | TrainersSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    discountCodes: DiscountCodesSelect<false> | DiscountCodesSelect<true>;
    partners: PartnersSelect<false> | PartnersSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    blogPosts: BlogPostsSelect<false> | BlogPostsSelect<true>;
    faqItems: FaqItemsSelect<false> | FaqItemsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    legalPages: LegalPagesSelect<false> | LegalPagesSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    eventPopups: EventPopupsSelect<false> | EventPopupsSelect<true>;
    eventRegistrations: EventRegistrationsSelect<false> | EventRegistrationsSelect<true>;
    eventEmails: EventEmailsSelect<false> | EventEmailsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('en' | 'ro') | ('en' | 'ro')[];
  globals: {
    siteSettings: SiteSetting;
    homepage: Homepage;
    expertBio: ExpertBio;
    corporatePage: CorporatePage;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    siteSettings: SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    expertBio: ExpertBioSelect<false> | ExpertBioSelect<true>;
    corporatePage: CorporatePageSelect<false> | CorporatePageSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: 'en' | 'ro';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      sendReviewRequests: TaskSendReviewRequests;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Dashboard user accounts only: administrators and editors. Site clients never get accounts and never log in; course participants are recorded on their orders instead.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Course presentation pages shown in the catalog. Each course holds only the shared content (title, description, audience); dates, prices and seats live on Course Sessions, one entry per edition.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses".
 */
export interface Course {
  id: number;
  title: string;
  /**
   * Auto-generated from "title" on first save. Edit to override — must stay unique.
   */
  slug?: string | null;
  /**
   * Short blurb shown on the course preview cards, for example in the "Explore our upcoming courses" section on the homepage. Keep it to one or two sentences; it does not appear on the course page itself.
   */
  shortDescription?: string | null;
  /**
   * Total course length in hours, shown on the catalog card and on the course page. Also used to calculate CPD credits, at 1 credit per hour.
   */
  durationHours?: number | null;
  /**
   * Reserved for future catalog filtering. The category is stored now, but the catalog shows no filter at launch.
   */
  category?: ('iso' | 'antiFraud' | 'security' | 'other') | null;
  /**
   * Full course description shown on the course page, below the header. Formatting (titles, quotes, colors) renders on the site exactly as set here.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The description above, as editable HTML. Change it here and save — the description is replaced with the parsed HTML (standard tags: h1-h6, p, blockquote, ul/ol, a, strong/em…). Note: brand text colors only survive when set in the visual editor, not through HTML.
   */
  descriptionHtml?: string | null;
  /**
   * The "Who this course is for" list on the course page. Add one row per bullet point; rows appear on the site in the order set here.
   */
  audience?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * The trainer profiles shown on the course page, under the enrolment card — one card per trainer, in this order. Leave empty to show the default (Dr. Silviu Gresoi); add trainers in the Trainers collection.
   */
  trainers?: (number | Trainer)[] | null;
  /**
   * CPD credits shown on the course page. Calculated automatically as 1 credit per course hour from Duration (hours); this field is used only when Duration is empty.
   */
  certificationCredits?: number | null;
  /**
   * The editions of this course, with their dates, prices and seats. Add or edit them in the Course Sessions collection; they appear here automatically.
   */
  sessions?: {
    docs?: (number | CourseSession)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  /**
   * Matching tags for the course quiz on the site. Fill these in so the quiz can recommend this course; leave Level empty to keep the course out of the quiz results entirely.
   */
  quizProfile?: {
    /**
     * Depth of the course. Required for the course to appear in quiz results; while empty, the quiz never recommends this course.
     */
    level?: ('introductory' | 'intermediate' | 'advanced' | 'specialization') | null;
    /**
     * What a participant walks away with at the end of the course. Pick all that apply; the quiz matches these against the visitor's answers.
     */
    outcomes?:
      | ('overview' | 'practicalSkills' | 'implementationPlan' | 'auditPrep' | 'certification' | 'foundationForMore')[]
      | null;
    /**
     * The domains this course covers, mirroring the quiz question about the visitor's field of interest. Pick all that apply.
     */
    domains?:
      | (
          'isoManagement' | 'quality' | 'sustainability' | 'riskCompliance' | 'infosec' | 'ai' | 'leadership' | 'audit'
        )[]
      | null;
    /**
     * One or two sentences shown on the quiz result screen as the reason this course is recommended. The quiz runs in Romanian, so write at least the Romanian version.
     */
    quizPitch?: string | null;
  };
  /**
   * The two cards at the bottom of the course page. Leave any field empty to use the default site copy; the left card always links to Corporate, the right one to Contact.
   */
  callouts?: {
    team?: {
      title?: string | null;
      body?: string | null;
    };
    questions?: {
      title?: string | null;
      body?: string | null;
    };
  };
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Trainer profiles shown on course pages, under the enrolment card. Assign one to a course via its Trainer field; courses without one show the default (Dr. Silviu Gresoi).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainers".
 */
export interface Trainer {
  id: number;
  /**
   * Full display name, including titles, e.g. "Dr. Silviu Gresoi, PhD, CFE".
   */
  name: string;
  /**
   * One line shown under the name, e.g. "Your trainer · 20+ years in AI, risk & financial crime".
   */
  role?: string | null;
  /**
   * Square portrait; shown as a small round photo. Without one, the default trainer photo is used.
   */
  photo?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * Editions of a course: dates, schedule, capacity and price windows. Each edition sells separately; the seat counts and the Early Bird or Standard prices shown on the site come from here.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseSessions".
 */
export interface CourseSession {
  id: number;
  course: number | Course;
  startDate: string;
  /**
   * The concrete days and hours this edition meets, shown in the program section of the course page. The latest day here also decides when the edition counts as past.
   */
  schedule?:
    | {
        date: string;
        /**
         * Start time of that day, 24-hour format, for example "09:00".
         */
        startTime: string;
        /**
         * End time of that day, 24-hour format, for example "17:00".
         */
        endTime: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Total seats for this edition. The site shows "X seats left" only when few remain, and sales stop automatically once every seat is sold.
   */
  capacity: number;
  /**
   * Seats consumed by confirmed orders. Updated automatically and atomically when a payment is confirmed; a refund releases the seats again. Do not edit by hand.
   */
  seatsSold?: number | null;
  /**
   * Timestamp set once the review-request emails have gone out to participants after this edition ended. The daily job checks it so nobody is emailed twice, even when a retry follows partial failures. Never set by hand.
   */
  reviewRequestSentAt?: string | null;
  /**
   * Early Bird price window. While the current date is inside this window, the site sells at this price. Leave everything empty if this edition has no Early Bird offer.
   */
  earlyBird?: {
    price?: number | null;
    /**
     * Price charged to visitors browsing from Romania (the currency is chosen by the visitor's location). Leave empty to sell this window in EUR only.
     */
    priceRON?: number | null;
    startDate?: string | null;
    /**
     * Last day of the Early Bird window. Leave both dates empty if this edition has no Early Bird window.
     */
    endDate?: string | null;
  };
  /**
   * Standard price window, used when the Early Bird window is not active. If neither window is active, the edition cannot be purchased and the site shows "Enrolment coming soon".
   */
  standard?: {
    price?: number | null;
    /**
     * Price charged to visitors browsing from Romania (the currency is chosen by the visitor's location). Leave empty to sell this window in EUR only.
     */
    priceRON?: number | null;
    startDate?: string | null;
    /**
     * Last day of the Standard window. Leave both dates empty if this edition has no Standard window.
     */
    endDate?: string | null;
  };
  /**
   * Calculated automatically as capacity minus seats sold. Read-only and never stored; a negative number means the edition was oversold and needs attention.
   */
  seatsRemaining?: number | null;
  /**
   * Derived automatically from the dates, the remaining seats and the price windows. Read-only and never stored; it changes on its own as time passes or seats sell.
   */
  status?: ('upcoming' | 'past' | 'soldOut' | 'noActiveWindow') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Orders placed through the site checkout, one course edition per order. Created and updated by the payment flow; use this list to review buyers, participants and payment status. Never exposed to the public API.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  session: number | CourseSession;
  quantity: number;
  buyer: {
    name: string;
    email: string;
    phone?: string | null;
    isCompany?: boolean | null;
    companyName?: string | null;
    cui?: string | null;
    address?: string | null;
  };
  /**
   * One row per seat; the number of rows must equal "quantity". For single-seat orders, checkout fills this in automatically from the buyer details.
   */
  participants?:
    | {
        name: string;
        email: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Snapshot of the full price breakdown at the moment of purchase: base price, applied window, discounts and total. Never recomputed afterwards and not hand-editable; it documents exactly what the buyer paid.
   */
  pricing?: {
    basePrice?: number | null;
    /**
     * Currency the buyer paid in, resolved from the visitor's location at purchase time: RON for Romania, EUR otherwise.
     */
    currency?: ('EUR' | 'RON') | null;
    appliedWindow?: ('earlyBird' | 'standard') | null;
    groupDiscount?: number | null;
    memberDiscount?: number | null;
    code?: (number | null) | DiscountCode;
    codes?: (number | DiscountCode)[] | null;
    codeDiscount?: number | null;
    total?: number | null;
  };
  paymentStatus: 'pending' | 'confirmed' | 'failed' | 'refunded';
  /**
   * Payment provider that handled this order, e.g. "mock" or "netopia". Set automatically by checkout; read-only.
   */
  provider?: string | null;
  /**
   * The provider's transaction or payment-session reference. Set automatically by checkout; read-only. Use it to find the payment in the provider's own dashboard.
   */
  providerRef?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Discount codes entered at checkout. Never publicly readable: the checkout validates a customer's code on the server, so visitors cannot list the valid codes.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discountCodes".
 */
export interface DiscountCode {
  id: number;
  code: string;
  percentage: number;
  expiresAt?: string | null;
  /**
   * Maximum number of orders that may use this code. Leave empty for unlimited uses; once the limit is reached, checkout rejects the code.
   */
  usageLimit?: number | null;
  /**
   * How many times checkout has applied this code so far. Increased automatically on each confirmed use. Do not edit by hand.
   */
  usageCount?: number | null;
  /**
   * General codes apply only their own percentage. Member codes additionally grant the member discount to the order, as if the buyer were an APCF member.
   */
  type: 'general' | 'member';
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Partner logos shown in the scrolling strip on the homepage (above the FAQ) and on the Corporate page (above the form). While this list is empty, the strip does not appear at all.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners".
 */
export interface Partner {
  id: number;
  /**
   * Partner name — used as the logo's alt text.
   */
  name: string;
  /**
   * Logo image, ideally SVG or PNG with a transparent background.
   */
  logo: number | Media;
  showOnHome?: boolean | null;
  showOnCorporate?: boolean | null;
  /**
   * Optional: the partner's website. When set, the logo becomes a link (opens in a new tab).
   */
  url?: string | null;
  /**
   * Position in the strip — lower numbers come first.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Participant testimonials, collected by email after a course edition ends or added manually. There is no star rating. Curate homepage placement with "Show on home"; at most 5 appear there.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  text: string;
  authorName?: string | null;
  roleCompany?: string | null;
  photo?: (number | null) | Media;
  /**
   * The course this testimonial refers to, if any. Optional; used for context in the dashboard.
   */
  course?: (number | null) | Course;
  source: 'emailForm' | 'manual';
  /**
   * Tick to feature this testimonial on the homepage. At most 5 ticked testimonials are displayed there; the rest stay hidden from visitors.
   */
  showOnHome?: boolean | null;
  /**
   * Duplicate-submission guard: sha256 of the session id and the lowercased email, set only by the public review submission route so the same (session, email) pair can submit at most once. Left empty for manually added reviews; the unique constraint allows any number of empty values.
   */
  submissionKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog articles shown on the Blog page. The rich text editor supports named brand colors, link chips (pill-style external links) and downloadable resources. The first publish of an article can also email newsletter subscribers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts".
 */
export interface BlogPost {
  id: number;
  title: string;
  /**
   * Auto-generated from "title" on first save. Edit to override — must stay unique.
   */
  slug?: string | null;
  /**
   * Cover image shown on the blog list card and at the top of the article. Optional: articles can be published without one and the layout adapts.
   */
  coverImage?: (number | null) | Media;
  excerpt?: string | null;
  /**
   * Article body shown on the article page. Supports colored text, blockquotes, images inside the text, link chips (pill-style external links) and downloadable resources.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Author name shown under the article title. Pre-filled with Dr. Silviu Gresoi and editable per article.
   */
  author?: string | null;
  /**
   * Reserved for future filtering of the blog list. The category is stored now, but the site shows no filter at launch.
   */
  category?: ('aiGovernance' | 'antiFraud' | 'riskManagement' | 'other') | null;
  /**
   * Reading time in minutes, shown on the blog card and on the article page. Leave empty to estimate it automatically from the body at about 200 words per minute; a value entered by hand always takes priority.
   */
  readingTime?: number | null;
  /**
   * When enabled, the article shows an email form that delivers the attached file to the reader after they submit their address.
   */
  leadMagnet?: {
    /**
     * Gate the file behind an email capture form.
     */
    enabled?: boolean | null;
    /**
     * Delivered to visitors who submit their email. Required while "enabled" is checked.
     */
    file?: (number | null) | Media;
  };
  /**
   * Links this article to a course. When set, a callout for that course appears at the end of the article; when empty, no callout is shown.
   */
  relatedCourse?: (number | null) | Course;
  /**
   * Uncheck to publish WITHOUT emailing subscribers. Only the first publish can trigger the newsletter broadcast, and it is sent at most once. Publishing while unchecked keeps that one send available: unpublish, tick the box and publish again to send it later.
   */
  sendNewsletterOnPublish?: boolean | null;
  /**
   * Set automatically once the first-publish newsletter broadcast has been attempted. Prevents the broadcast from being sent again on later saves or re-publishes. Do not edit by hand.
   */
  broadcastSentAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Questions and answers shown in the FAQ section on the homepage, grouped into journey tabs (Discover, Learn, Validate, Access). Changes appear on the site after saving.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqItems".
 */
export interface FaqItem {
  id: number;
  question: string;
  answer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * The tab this question appears under in the homepage FAQ section. Each tab matches a stage of the visitor journey, from discovering the site to enrolling.
   */
  category?: ('discover' | 'learn' | 'validate' | 'access') | null;
  /**
   * Position of the question within its tab, sorted ascending: lower numbers appear higher in the list.
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the Contact and Corporate forms on the site. Every new entry also triggers a notification email to the site contact address. Entries are created by visitors; only administrators can view or manage them.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  type: 'contact' | 'corporate';
  name: string;
  email: string;
  phone?: string | null;
  message?: string | null;
  /**
   * Contact form only: the topic the visitor picked in the subject dropdown.
   */
  subject?: ('course' | 'corporate' | 'certification' | 'other') | null;
  /**
   * Corporate form only: the company the request comes from.
   */
  companyName?: string | null;
  /**
   * Corporate form only: the person to follow up with at the company.
   */
  contactPerson?: string | null;
  /**
   * Corporate form only: estimated number of participants, free text, e.g. "10-20".
   */
  participantsRange?: string | null;
  /**
   * Corporate form only: the existing catalog course the company asked about.
   */
  topicCourse?: (number | null) | Course;
  /**
   * Corporate form only: free-text topic, used when the request is not about one of the catalog courses.
   */
  topicOther?: string | null;
  /**
   * Corporate form only: the visitor's answers to the configurable form fields (set up on the Corporate Page global), exactly as submitted.
   */
  formData?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Corporate form only: the delivery window the company prefers (from and to dates).
   */
  preferredPeriod?: {
    from?: string | null;
    to?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * The full text of the legal pages: Terms, Privacy, Cookies. What you save here is exactly what visitors read on the site; nothing is hard-coded any more, and every save republishes the pages in both languages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages".
 */
export interface LegalPage {
  id: number;
  /**
   * Which page of the site this document renders on. Create exactly one document per page; the value cannot repeat.
   */
  page: 'terms' | 'privacy' | 'cookies';
  /**
   * Title shown in the browser tab and used by search engines, e.g. "Terms and Conditions".
   */
  metaTitle: string;
  /**
   * First part of the on-page heading, rendered in plain ink, e.g. "Terms and " (mind the trailing space).
   */
  titlePlain?: string | null;
  /**
   * Last part of the on-page heading, rendered in the brand gradient, e.g. "Conditions."
   */
  titleGradient?: string | null;
  /**
   * Shown verbatim under the title, e.g. "Last updated: 21.07.2026". Free text on purpose: it is the date of the document itself, not of the last save, and the two must not be confused.
   */
  lastUpdated?: string | null;
  /**
   * The numbered sections of the document, in the order they appear on the page. Put the number in the heading itself, e.g. "1. General information". Leave the heading empty for the preamble.
   */
  sections?:
    | {
        /**
         * The section heading, copied verbatim from the document. Leave empty for a section without a heading (the preamble).
         */
        heading?: string | null;
        blocks?:
          | (
              | {
                  text: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'paragraph';
                }
              | {
                  /**
                   * e.g. "3.1. Provider" or "Identification data".
                   */
                  text: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'subheading';
                }
              | {
                  items?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'list';
                }
              | {
                  headLeft: string;
                  headRight: string;
                  rows?:
                    | {
                        left: string;
                        right: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'table';
                }
              | {
                  /**
                   * First line of the panel, e.g. the legal name and registration numbers.
                   */
                  line1: string;
                  /**
                   * Second line of the panel, e.g. contact emails, phone, website.
                   */
                  line2: string;
                  id?: string | null;
                  blockName?: string | null;
                  blockType: 'entity';
                }
            )[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Write a newsletter in the dashboard and broadcast it to every subscriber on the Brevo list. Tick "Send now" and save: the message goes out once and cannot be re-sent.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: number;
  /**
   * The subject line recipients see in their inbox.
   */
  subject: string;
  /**
   * Optional one-line intro shown under the title in the email. Leave empty to skip it.
   */
  preheader?: string | null;
  /**
   * The body of the message. Headings, bold, italic, links and lists are carried into the email; images and embeds are not.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Tick and save to send the newsletter to all subscribers. Sending happens exactly once and cannot be undone.
   */
  sendNow?: boolean | null;
  /**
   * Set automatically at the moment the newsletter went out. Once this date exists, the newsletter can never be sent again.
   */
  sentAt?: string | null;
  /**
   * Outcome of the last send attempt. Check here first if the newsletter did not arrive.
   */
  lastResult?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * One entry per live event. A pop-up shows on the site only while its status is "Published" AND the current time is between "Start showing at" and the event date; after the event it disappears on its own. "Registrations" counts the people who signed up for that event; their details are in Event Registrations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventPopups".
 */
export interface EventPopup {
  id: number;
  /**
   * Internal name used only in this admin list, to tell events apart. Never shown to visitors.
   */
  internalName: string;
  /**
   * Auto-generated from "internalName" on first save. Edit to override — must stay unique.
   */
  slug?: string | null;
  /**
   * Only "Published" pop-ups can ever appear on the site; drafts and archived entries are never shown to visitors.
   */
  status: 'draft' | 'published' | 'archived';
  /**
   * Increased automatically by "Force re-show". Visitors who dismissed an older version of the pop-up will see the new version again.
   */
  displayVersion?: number | null;
  /**
   * Tick and save to show this pop-up again to visitors who dismissed it. People who already registered never see it again. The box un-ticks itself after saving.
   */
  forceReshow?: boolean | null;
  /**
   * Event title, the part rendered in the plain ink color, for example "AI Governance ". Keep the trailing space if the gradient segment continues the sentence.
   */
  titlePlain?: string | null;
  /**
   * Event title, the segment rendered in the brand gradient, for example "in Practice.". Displayed right after the plain part.
   */
  titleGradient?: string | null;
  description?: string | null;
  /**
   * Short info line shown under the title, for example "Thu 14 Aug 2026 · 18:00 (EEST) · Live on Zoom".
   */
  metaLine?: string | null;
  /**
   * Speakers shown in the pop-up, each with their photo, or with initials when no photo is uploaded.
   */
  speakers?:
    | {
        name: string;
        role?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Label of the main button in the pop-up. When empty, the site shows "Secure your spot".
   */
  ctaLabel?: string | null;
  /**
   * Label of the registration form submit button. When empty, the site shows "Join us".
   */
  joinLabel?: string | null;
  /**
   * Options offered in the occupation list of the registration form. Visitors can also type their own answer.
   */
  occupations?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Date and time of the event, used as the countdown target. The pop-up disappears on its own after this moment; there is no need to unpublish it.
   */
  eventDate: string;
  /**
   * The moment from which the pop-up may start appearing on the site. Must be before the event date.
   */
  startShowingAt: string;
  /**
   * How many seconds a visitor stays on the page before the pop-up appears.
   */
  showDelaySeconds?: number | null;
  /**
   * Shows the newsletter opt-in checkbox (unticked by default) in the registration form. Untick to hide the opt-in entirely for this event.
   */
  newsletterOptInEnabled?: boolean | null;
  /**
   * The wording shown next to the newsletter opt-in. Stored as a snapshot on every registration, as GDPR proof of exactly what was agreed to.
   */
  newsletterConsentText?: string | null;
  /**
   * How many people signed up for this event. Counted live from Event Registrations; read-only.
   */
  registrationsCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Everyone who signed up through an event pop-up. Each row belongs to ONE event, shown in the "Popup" column; use Filters, then Popup, to see a single event's list. Signing up for one event never signs anyone up for another, and it does not subscribe them to the newsletter unless they ticked that box.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations".
 */
export interface EventRegistration {
  id: number;
  /**
   * The event pop-up this sign-up came from. Determines which event the person registered for.
   */
  popup: number | EventPopup;
  firstName: string;
  lastName: string;
  email: string;
  /**
   * The occupation the person chose from the configured list or typed in freely on the registration form.
   */
  occupation?: string | null;
  /**
   * Whether the person ticked the newsletter box when registering. This alone does NOT make them a subscriber; they still have to confirm the double opt-in e-mail.
   */
  newsletterOptIn?: boolean | null;
  /**
   * GDPR proof: the exact consent wording agreed to, and when. Kept as a snapshot because the pop-up's consent text can be edited later; the proof must not change with it.
   */
  consentSnapshot?: {
    consentText?: string | null;
    consentedAt?: string | null;
    ip?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Write an e-mail and send it to everyone registered for ONE event. Tick "Send test to me" first to check how it looks in your own inbox; then "Send now" delivers it to the whole list. Each document sends only once and cannot be re-sent; after sending it stays here as a log of the delivery.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventEmails".
 */
export interface EventEmail {
  id: number;
  /**
   * The event whose registrants receive this e-mail. Only people registered for that event get it; nobody else does.
   */
  popup: number | EventPopup;
  /**
   * Subject line of the e-mail. Variables work here too, for example {{firstName}}.
   */
  subject: string;
  /**
   * Body of the e-mail. The variables {{firstName}}, {{lastName}}, {{eventTitle}}, {{eventDate}} and {{joinUrl}} are replaced per recipient. Headings, bold, links and lists carry into the e-mail; images and embeds do not.
   */
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Zoom or Meet link, filled in per e-mail rather than on the event: the link often does not exist yet when the pop-up is created, and a reminder may point somewhere different from the invitation. Becomes the {{joinUrl}} variable. Leave empty if this e-mail does not need it.
   */
  joinUrl?: string | null;
  /**
   * Sends ONE copy to your own admin account e-mail, with sample names filled into the variables. Changes nothing else; use it as the preview before the real send.
   */
  sendTestNow?: boolean | null;
  /**
   * Tick and save to send the e-mail to every registrant of the selected event. Works ONCE: re-saving afterwards sends nothing. If some addresses failed, ticking it again retries only those addresses.
   */
  sendNow?: boolean | null;
  status?: ('draft' | 'sent' | 'failed') | null;
  /**
   * The outcome of the last send attempt, written automatically. Check it after ticking one of the send boxes.
   */
  lastResult?: string | null;
  sentAt?: string | null;
  /**
   * Which admin pressed send. This is an audit trail, NOT the sender address: e-mails always go out from the newsletter sender, news@isad.academy.
   */
  sentBy?: (number | null) | User;
  recipientCount?: number | null;
  successCount?: number | null;
  /**
   * Addresses the e-mail provider refused, with the reason for each. Ticking "Send now" again retries exactly these addresses and no others.
   */
  failures?:
    | {
        email?: string | null;
        error?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'sendReviewRequests';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'sendReviewRequests') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'courses';
        value: number | Course;
      } | null)
    | ({
        relationTo: 'courseSessions';
        value: number | CourseSession;
      } | null)
    | ({
        relationTo: 'trainers';
        value: number | Trainer;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'discountCodes';
        value: number | DiscountCode;
      } | null)
    | ({
        relationTo: 'partners';
        value: number | Partner;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'blogPosts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'faqItems';
        value: number | FaqItem;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'legalPages';
        value: number | LegalPage;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'eventPopups';
        value: number | EventPopup;
      } | null)
    | ({
        relationTo: 'eventRegistrations';
        value: number | EventRegistration;
      } | null)
    | ({
        relationTo: 'eventEmails';
        value: number | EventEmail;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courses_select".
 */
export interface CoursesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  shortDescription?: T;
  durationHours?: T;
  category?: T;
  description?: T;
  descriptionHtml?: T;
  audience?:
    | T
    | {
        text?: T;
        id?: T;
      };
  trainers?: T;
  certificationCredits?: T;
  sessions?: T;
  quizProfile?:
    | T
    | {
        level?: T;
        outcomes?: T;
        domains?: T;
        quizPitch?: T;
      };
  callouts?:
    | T
    | {
        team?:
          | T
          | {
              title?: T;
              body?: T;
            };
        questions?:
          | T
          | {
              title?: T;
              body?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "courseSessions_select".
 */
export interface CourseSessionsSelect<T extends boolean = true> {
  course?: T;
  startDate?: T;
  schedule?:
    | T
    | {
        date?: T;
        startTime?: T;
        endTime?: T;
        id?: T;
      };
  capacity?: T;
  seatsSold?: T;
  reviewRequestSentAt?: T;
  earlyBird?:
    | T
    | {
        price?: T;
        priceRON?: T;
        startDate?: T;
        endDate?: T;
      };
  standard?:
    | T
    | {
        price?: T;
        priceRON?: T;
        startDate?: T;
        endDate?: T;
      };
  seatsRemaining?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trainers_select".
 */
export interface TrainersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  session?: T;
  quantity?: T;
  buyer?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
        isCompany?: T;
        companyName?: T;
        cui?: T;
        address?: T;
      };
  participants?:
    | T
    | {
        name?: T;
        email?: T;
        id?: T;
      };
  pricing?:
    | T
    | {
        basePrice?: T;
        currency?: T;
        appliedWindow?: T;
        groupDiscount?: T;
        memberDiscount?: T;
        code?: T;
        codes?: T;
        codeDiscount?: T;
        total?: T;
      };
  paymentStatus?: T;
  provider?: T;
  providerRef?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "discountCodes_select".
 */
export interface DiscountCodesSelect<T extends boolean = true> {
  code?: T;
  percentage?: T;
  expiresAt?: T;
  usageLimit?: T;
  usageCount?: T;
  type?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "partners_select".
 */
export interface PartnersSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  showOnHome?: T;
  showOnCorporate?: T;
  url?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  text?: T;
  authorName?: T;
  roleCompany?: T;
  photo?: T;
  course?: T;
  source?: T;
  showOnHome?: T;
  submissionKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogPosts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  coverImage?: T;
  excerpt?: T;
  body?: T;
  author?: T;
  category?: T;
  readingTime?: T;
  leadMagnet?:
    | T
    | {
        enabled?: T;
        file?: T;
      };
  relatedCourse?: T;
  sendNewsletterOnPublish?: T;
  broadcastSentAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqItems_select".
 */
export interface FaqItemsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  category?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  type?: T;
  name?: T;
  email?: T;
  phone?: T;
  message?: T;
  subject?: T;
  companyName?: T;
  contactPerson?: T;
  participantsRange?: T;
  topicCourse?: T;
  topicOther?: T;
  formData?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  preferredPeriod?:
    | T
    | {
        from?: T;
        to?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legalPages_select".
 */
export interface LegalPagesSelect<T extends boolean = true> {
  page?: T;
  metaTitle?: T;
  titlePlain?: T;
  titleGradient?: T;
  lastUpdated?: T;
  sections?:
    | T
    | {
        heading?: T;
        blocks?:
          | T
          | {
              paragraph?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              subheading?:
                | T
                | {
                    text?: T;
                    id?: T;
                    blockName?: T;
                  };
              list?:
                | T
                | {
                    items?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              table?:
                | T
                | {
                    headLeft?: T;
                    headRight?: T;
                    rows?:
                      | T
                      | {
                          left?: T;
                          right?: T;
                          id?: T;
                        };
                    id?: T;
                    blockName?: T;
                  };
              entity?:
                | T
                | {
                    line1?: T;
                    line2?: T;
                    id?: T;
                    blockName?: T;
                  };
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  subject?: T;
  preheader?: T;
  body?: T;
  sendNow?: T;
  sentAt?: T;
  lastResult?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventPopups_select".
 */
export interface EventPopupsSelect<T extends boolean = true> {
  internalName?: T;
  slug?: T;
  status?: T;
  displayVersion?: T;
  forceReshow?: T;
  titlePlain?: T;
  titleGradient?: T;
  description?: T;
  metaLine?: T;
  speakers?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  ctaLabel?: T;
  joinLabel?: T;
  occupations?:
    | T
    | {
        label?: T;
        id?: T;
      };
  eventDate?: T;
  startShowingAt?: T;
  showDelaySeconds?: T;
  newsletterOptInEnabled?: T;
  newsletterConsentText?: T;
  registrationsCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventRegistrations_select".
 */
export interface EventRegistrationsSelect<T extends boolean = true> {
  popup?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  occupation?: T;
  newsletterOptIn?: T;
  consentSnapshot?:
    | T
    | {
        consentText?: T;
        consentedAt?: T;
        ip?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "eventEmails_select".
 */
export interface EventEmailsSelect<T extends boolean = true> {
  popup?: T;
  subject?: T;
  body?: T;
  joinUrl?: T;
  sendTestNow?: T;
  sendNow?: T;
  status?: T;
  lastResult?: T;
  sentAt?: T;
  sentBy?: T;
  recipientCount?: T;
  successCount?: T;
  failures?:
    | T
    | {
        email?: T;
        error?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site-wide configuration: currency, price window display, discount stacking policy, legal entity details, contact info and analytics IDs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings".
 */
export interface SiteSetting {
  id: number;
  /**
   * The "X seats left" badge on a course edition appears only when the remaining seats drop below this number. Set 0 to never show it.
   */
  seatsThreshold?: number | null;
  /**
   * The site-wide currency setting used when displaying course prices. Default: EUR.
   */
  currency?: ('EUR' | 'RON') | null;
  /**
   * Whether prices across the site are presented as VAT included or VAT excluded. Default: VAT included.
   */
  vatDisplay?: ('incl' | 'excl') | null;
  /**
   * Controls the price block on the course page: show both the Early Bird and Standard price windows, or only the one currently active. Default: show both windows.
   */
  earlyBirdDisplay?: ('bothWindows' | 'activeOnly') | null;
  /**
   * How the group, member and discount-code reductions combine at checkout. All three strategies are implemented; this setting only selects which one applies. Changing it affects every new order immediately. Default: stack all discounts.
   */
  stackingPolicy?: ('stackAll' | 'bestOf' | 'groupMemberStack_codeExclusive') | null;
  /**
   * Legal entity details shown in the site footer and used on invoices: company name, CUI, address and the ANPC dispute-resolution links. The footer simply omits whatever is left empty.
   */
  legalEntity?: {
    name?: string | null;
    cui?: string | null;
    address?: string | null;
    anpcUrl?: string | null;
    solUrl?: string | null;
  };
  contact?: {
    email?: string | null;
    phone?: string | null;
    linkedin?: string | null;
  };
  /**
   * Optional overrides for the GA4 and GTM IDs configured through environment variables. The scripts load lazily and only after cookie consent, so filling these in never affects visitors who declined.
   */
  analytics?: {
    ga4Id?: string | null;
    gtmId?: string | null;
    gscVerification?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage content: the hero section, the featured course selection, the trust stats and differentiators, and the newsletter block. Saving republishes the homepage in both languages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero?: {
    title?: string | null;
    subtitle?: string | null;
    ctaText?: string | null;
    ctaLink?: string | null;
  };
  /**
   * The courses shown in the "Featured courses" section of the homepage, in the order set here. The selection is manual; nothing is picked automatically.
   */
  featuredCourses?: (number | Course)[] | null;
  whyIsad?: {
    stats?:
      | {
          value?: string | null;
          label?: string | null;
          id?: string | null;
        }[]
      | null;
    differentiators?:
      | {
          title?: string | null;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  newsletter?: {
    headline?: string | null;
    invitationText?: string | null;
    /**
     * Optional: offer a downloadable resource in exchange for a newsletter signup, shown with the newsletter block on the homepage.
     */
    leadMagnet?: {
      /**
       * Gate the file behind an email capture form.
       */
      enabled?: boolean | null;
      /**
       * Delivered to visitors who submit their email. Required while "enabled" is checked.
       */
      file?: (number | null) | Media;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The trainer biography, reused across the site: the short bio appears in the expert band on the homepage, the full bio on the About page. Saving republishes both pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertBio".
 */
export interface ExpertBio {
  id: number;
  name?: string | null;
  /**
   * Professional title or headline shown next to the name, e.g. the role and main credential.
   */
  title?: string | null;
  photo?: (number | null) | Media;
  /**
   * Short biography shown in the expert band on the homepage.
   */
  shortBio?: string | null;
  /**
   * Full biography shown on the About page.
   */
  fullBio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  credentials?:
    | {
        label?: string | null;
        value?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Content of the Corporate page: hero, benefit cards, industries, the proposal form (including its optional fields) and the side column. Empty fields fall back to the built-in copy. Saving republishes the page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corporatePage".
 */
export interface CorporatePage {
  id: number;
  hero?: {
    pill?: string | null;
    /**
     * First title line, e.g. "Help your organization".
     */
    titleTop?: string | null;
    /**
     * Start of the second line, before the highlighted phrase.
     */
    titleBottomPrefix?: string | null;
    /**
     * The gradient-highlighted phrase that ends the title.
     */
    titleBottomHighlight?: string | null;
    subtitle?: string | null;
    ctaPrimary?: string | null;
    ctaSecondary?: string | null;
  };
  benefits?: {
    /**
     * Plain part of the section title, e.g. "One expert.".
     */
    titlePlain?: string | null;
    /**
     * Gradient-highlighted part of the section title.
     */
    titleHighlight?: string | null;
    /**
     * The three (or more) benefit cards. When empty, the default three cards are shown.
     */
    items?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    idealFor?: string | null;
    industries?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
  };
  form?: {
    title?: string | null;
    subtitle?: string | null;
    /**
     * The form fields AFTER the fixed ones (company name, contact person, e-mail — always shown and required). Add, remove or reorder rows freely; answers are stored on the lead and included in the notification e-mail. When the list is empty, the default fields are shown (phone, participants, topic, preferred period, message).
     */
    fields?:
      | {
          /**
           * Shown as the field placeholder and stored next to the answer.
           */
          label: string;
          fieldType: 'text' | 'email' | 'phone' | 'textarea' | 'select' | 'courseTopic' | 'period';
          required?: boolean | null;
          /**
           * The choices of the dropdown, in order.
           */
          options?:
            | {
                option: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  aside?: {
    nextTitle?: string | null;
    steps?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    talkTitle?: string | null;
    talkNote?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "siteSettings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  seatsThreshold?: T;
  currency?: T;
  vatDisplay?: T;
  earlyBirdDisplay?: T;
  stackingPolicy?: T;
  legalEntity?:
    | T
    | {
        name?: T;
        cui?: T;
        address?: T;
        anpcUrl?: T;
        solUrl?: T;
      };
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        linkedin?: T;
      };
  analytics?:
    | T
    | {
        ga4Id?: T;
        gtmId?: T;
        gscVerification?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        title?: T;
        subtitle?: T;
        ctaText?: T;
        ctaLink?: T;
      };
  featuredCourses?: T;
  whyIsad?:
    | T
    | {
        stats?:
          | T
          | {
              value?: T;
              label?: T;
              id?: T;
            };
        differentiators?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
      };
  newsletter?:
    | T
    | {
        headline?: T;
        invitationText?: T;
        leadMagnet?:
          | T
          | {
              enabled?: T;
              file?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "expertBio_select".
 */
export interface ExpertBioSelect<T extends boolean = true> {
  name?: T;
  title?: T;
  photo?: T;
  shortBio?: T;
  fullBio?: T;
  credentials?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "corporatePage_select".
 */
export interface CorporatePageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        pill?: T;
        titleTop?: T;
        titleBottomPrefix?: T;
        titleBottomHighlight?: T;
        subtitle?: T;
        ctaPrimary?: T;
        ctaSecondary?: T;
      };
  benefits?:
    | T
    | {
        titlePlain?: T;
        titleHighlight?: T;
        items?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        idealFor?: T;
        industries?:
          | T
          | {
              name?: T;
              id?: T;
            };
      };
  form?:
    | T
    | {
        title?: T;
        subtitle?: T;
        fields?:
          | T
          | {
              label?: T;
              fieldType?: T;
              required?: T;
              options?:
                | T
                | {
                    option?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  aside?:
    | T
    | {
        nextTitle?: T;
        steps?:
          | T
          | {
              text?: T;
              id?: T;
            };
        talkTitle?: T;
        talkNote?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSendReviewRequests".
 */
export interface TaskSendReviewRequests {
  input?: unknown;
  output: {
    sessionsProcessed?: number | null;
    emailsSent?: number | null;
    emailsFailed?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "LinkChipBlock".
 */
export interface LinkChipBlock {
  /**
   * Button text, e.g. "Watch the interview".
   */
  label: string;
  /**
   * Absolute http(s) URL the chip links to.
   */
  url: string;
  /**
   * Shown next to the label so readers know where the link leads.
   */
  platform?: ('youtube' | 'linkedin' | 'website' | 'other') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'linkChip';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DownloadableResourceBlock".
 */
export interface DownloadableResourceBlock {
  title: string;
  /**
   * Optional one-liner shown under the title.
   */
  description?: string | null;
  file: number | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'downloadableResource';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}